repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v14.0.0'  # The default in Ubuntu 22.04, which is used in our CI
  hooks:
  - id: clang-format
    types_or: [c, c++, cuda, inc]
    exclude: |
      (?x)^(
        third_party/SuiteSparse/AMD/.*|
        third_party/identify_stream_usage/.*
      )
- repo: local
  hooks:
    - id: update-ginkgo-header
      name: update ginkgo.hpp header
      language: system
      entry: python3 dev_tools/scripts/update-ginkgo-header.py
      files: \.hpp$
