# SPDX-FileCopyrightText: 2017-2023 The Ginkgo authors
#
# SPDX-License-Identifier: BSD-3-Clause

coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 5
        base: auto
        informational: True
    project:
      default:
        target: auto
        threshold: 2
        base: auto
  ignore:
    - "examples"
    - "benchmark"
