/*******************************<GINKGO LICENSE>******************************
Copyright (c) 2017-2023, the Ginkgo authors
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************<GINKGO LICENSE>*******************************/

#ifndef GKO_PUBLIC_CORE_LOG_BATCH_CONVERGENCE_HPP_
#define GKO_PUBLIC_CORE_LOG_BATCH_CONVERGENCE_HPP_


#include <memory>


#include <ginkgo/core/base/batch_multi_vector.hpp>
#include <ginkgo/core/base/types.hpp>
#include <ginkgo/core/log/logger.hpp>


namespace gko {
namespace batch {
/**
 * @brief The logger namespace .
 * @ref log
 * @ingroup log
 */
namespace log {


/**
 * Types of batch loggers available.
 */
enum class BatchLogType {
    convergence_completion,
    simple_convergence_completion
};


struct BatchLogDataBase {
    /**
     * Stores convergence iteration counts for every matrix in the batch and
     * for every right-hand side.
     */
    array<int> iter_counts;

    virtual ~BatchLogDataBase() = default;
};


/**
 * Stores logging data for batch solver kernels.
 */
template <typename ValueType>
struct BatchLogData : public BatchLogDataBase {
    /**
     * Stores residual norm values for every linear system in the batch
     * for every right-hand side.
     */
    std::shared_ptr<MultiVector<remove_complex<ValueType>>> res_norms;
};


/**
 * Logs the final residuals and iteration counts for a batch solver.
 *
 * The purpose of this logger is to give simple access to standard data
 * generated by the solver once it has converged.
 *
 * @ingroup log
 */
template <typename ValueType = default_precision>
class BatchConvergence : public gko::log::Logger {
public:
    using real_type = remove_complex<ValueType>;
    using mask_type = gko::log::Logger::mask_type;

    /**
     * Copies arrays of iterations and residual norms into this (on the host).
     *
     * The arguments can be on any executor and the data is copied to the host
     * executor.
     * TODO: Move to gko::log::Logger class and override here when a non-value
     * type MultiVector base is available.
     *
     * @param iteration_count  Array (size number of matrices x number of
     *     right-hand sides) which stores the iteration count at which each RHS
     *     of each linear system converged. The convergence iteration count for
     *     the different RHS are stored contiguously.
     * @param residual_norm  A MultiVector of size
     *     num_matrices x 1 x num_RHS, which stores the final residual norms.
     */
    void on_batch_solver_completed(
        const array<int>& iteration_count,
        const MultiVector<real_type>* const residual_norm) const;

    /**
     * Creates a convergence logger. This dynamically allocates the memory,
     * constructs the object and returns an std::unique_ptr to this object.
     *
     * @param exec  the executor
     * @param enabled_events  the events enabled for this logger. By default all
     *                        events.
     *
     * @return an std::unique_ptr to the the constructed object
     */
    static std::unique_ptr<BatchConvergence> create(
        std::shared_ptr<const Executor> exec,
        const mask_type& enabled_events = gko::log::Logger::all_events_mask)
    {
        return std::unique_ptr<BatchConvergence>(
            new BatchConvergence(exec, enabled_events));
    }

    /**
     * @return  The number of iterations for entire batch
     */
    const array<int>& get_num_iterations() const noexcept
    {
        return iteration_count_;
    }

    /**
     * @return  The residual norms for the entire batch.
     */
    const MultiVector<real_type>* get_residual_norm() const noexcept
    {
        return residual_norm_.get();
    }

protected:
    /**
     * Creates a batch convergence logger.
     *
     * @param exec  the executor
     * @param enabled_events  the events enabled for this logger. By default all
     *                        events.
     */
    explicit BatchConvergence(
        std::shared_ptr<const Executor> exec,
        const mask_type& enabled_events = gko::log::Logger::all_events_mask)
        : gko::log::Logger(enabled_events),
          iteration_count_(exec->get_master()),
          residual_norm_(MultiVector<real_type>::create(exec->get_master()))
    {}

private:
    mutable array<int> iteration_count_;
    mutable std::unique_ptr<MultiVector<real_type>> residual_norm_{};
};


}  // namespace log
}  // namespace batch
}  // namespace gko


#endif  // GKO_PUBLIC_CORE_LOG_BATCH_CONVERGENCE_HPP_
