ginkgo_print_module_header(${detailed_log} "MPI")
ginkgo_print_variable(${detailed_log} "MPI_CXX_COMPILER")
ginkgo_print_variable(${detailed_log} "MPI_CXX_COMPILE_OPTIONS")
ginkgo_print_variable(${detailed_log} "MPI_CXX_LINK_FLAGS")
ginkgo_print_variable(${detailed_log} "MPI_CXX_LIB_NAMES")
ginkgo_print_variable(${detailed_log} "MPI_CXX_HEADER_DIR")
ginkgo_print_variable(${detailed_log} "MPI_CXX_LIBRARY")
ginkgo_print_variable(${detailed_log} "MPIEXEC_EXECUTABLE")
ginkgo_print_variable(${detailed_log} "MPIEXEC_MAX_NUMPROCS")
ginkgo_print_variable(${detailed_log} "MPIEXEC_NUMPROC_FLAG")
ginkgo_print_module_footer(${detailed_log} "MPI variables:")
ginkgo_print_module_footer(${detailed_log} "")
