// SPDX-FileCopyrightText: 2017 - 2026 The Ginkgo authors
//
// SPDX-License-Identifier: BSD-3-Clause

#ifndef GKO_PUBLIC_CORE_BASE_POLYMORPHIC_OBJECT_HPP_
#define GKO_PUBLIC_CORE_BASE_POLYMORPHIC_OBJECT_HPP_


#include <memory>
#include <type_traits>

#include <ginkgo/core/base/executor.hpp>
#include <ginkgo/core/base/utils.hpp>
#include <ginkgo/core/log/logger.hpp>


namespace gko {
namespace experimental {
namespace distributed {


class DistributedBase;


}  // namespace distributed
}  // namespace experimental


/**
 * A PolymorphicObject is the abstract base for all "heavy" objects in Ginkgo
 * that behave polymorphically.
 *
 * It defines the basic utilities (copying moving, cloning, clearing the
 * objects) for all such objects. It takes into account that these objects are
 * dynamically allocated, managed by smart pointers, and used polymorphically.
 * Additionally, it assumes their data can be allocated on different executors,
 * and that they can be copied between those executors.
 *
 * @note Most of the public methods of this class should not be overridden
 *       directly, and are thus not virtual. Instead, there are equivalent
 *       protected methods (ending in <method_name>_impl) that should be
 *       overridden instead. This allows polymorphic objects to implement
 *       default behavior around virtual methods (parameter checking, type
 *       casting).
 */
class PolymorphicObject : public log::EnableLogging<PolymorphicObject> {
public:
    virtual ~PolymorphicObject()
    {
        this->template log<log::Logger::polymorphic_object_deleted>(exec_.get(),
                                                                    this);
    }

    /**
     * Throws gko::InvalidData exception if
     * we found the data inside the object
     * does not fulfill certain property up to our knowledge.
     */
    virtual void validate_data() const {}

    // preserve the executor of the object
    PolymorphicObject& operator=(const PolymorphicObject&) { return *this; }

    /**
     * Returns the Executor of the object.
     *
     * @return Executor of the object
     */
    std::shared_ptr<const Executor> get_executor() const noexcept
    {
        return exec_;
    }

protected:
    // This method is defined as protected since a polymorphic object should not
    // be created using their constructor directly, but by creating an
    // std::unique_ptr to it. Defining the constructor as protected keeps these
    // access rights when inheriting the constructor.
    /**
     * Creates a new polymorphic object on the requested executor.
     *
     * @param exec  executor where the object will be created
     */
    explicit PolymorphicObject(std::shared_ptr<const Executor> exec)
        : exec_{std::move(exec)}
    {}

    // preserve the executor of the object
    explicit PolymorphicObject(const PolymorphicObject& other)
    {
        *this = other;
    }

private:
    std::shared_ptr<const Executor> exec_;
};


/**
 * This macro implements the `self()` method, which is a shortcut for
 * `static_cast<_type *>(this)`.
 *
 * It also provides a constant version overload. It is often useful when
 * implementing mixins which depend on the type of the affected object, in which
 * case the type is set to the affected object (i.e. the CRTP parameter).
 */
#define GKO_ENABLE_SELF(_type)                                   \
    _type* self() noexcept { return static_cast<_type*>(this); } \
                                                                 \
    const _type* self() const noexcept                           \
    {                                                            \
        return static_cast<const _type*>(this);                  \
    }


/**
 * ConvertibleTo interface is used to mark that the implementer can be converted
 * to the object of ResultType.
 *
 * This interface is used to enable conversions between polymorphic objects.
 * To mark that an object of type `U` can be converted to an object of type `V`,
 * `U` should implement ConvertibleTo<V>.
 * Then, the implementation of `Cloneable::copy_from` automatically
 * generated by `EnableCloneable` mixin will use RTTI to figure out that
 * `U` implements the interface and convert it using the convert_to / move_to
 * methods of the interface.
 *
 * As an example, the following function:
 *
 * ```c++
 * void my_function(const U *u, V *v) {
 *     v->copy_from(u);
 * }
 * ```
 *
 * will convert object `u` to object `v` by checking that `u` can be dynamically
 * casted to `ConvertibleTo\<V\>`, and calling
 * ConvertibleTo\<V\>::convert_to(V*)` to do the actual conversion.
 *
 * In case `u` is passed as a unique_ptr, call to `convert_to` will be replaced
 * by a call to `move_to` and trigger move semantics.
 *
 * @tparam ResultType  the type to which the implementer can be converted to,
 *                     has to be a subclass of PolymorphicObject
 */
template <typename ResultType>
class ConvertibleTo {
public:
    using result_type = ResultType;

    virtual ~ConvertibleTo() = default;

    /**
     * Converts the implementer to an object of type result_type.
     *
     * @param result  the object used to store the result of the conversion
     */
    virtual void convert_to(result_type* result) const = 0;

    void convert_to(ptr_param<result_type> result) const
    {
        convert_to(result.get());
    }

    /**
     * Converts the implementer to an object of type result_type by moving data
     * from this object.
     *
     * This method is used when the implementer is a temporary object, and move
     * semantics can be used.
     *
     * @param result  the object used to emplace the result of the conversion
     *
     * @note ConvertibleTo::move_to can be implemented by simply calling
     *       ConvertibleTo::convert_to. However, this operation can often be
     *       optimized by exploiting the fact that implementer's data can be
     *       moved to the result.
     */
    virtual void move_to(result_type* result) = 0;

    void move_to(ptr_param<result_type> result) { move_to(result.get()); }
};


namespace detail {


template <typename R, typename T>
std::unique_ptr<R, std::function<void(R*)>> copy_and_convert_to_impl(
    std::shared_ptr<const Executor> exec, T* obj)
{
    auto obj_as_r = dynamic_cast<R*>(obj);
    if (obj_as_r != nullptr && obj->get_executor() == exec) {
        // FIXME: this breaks lifetimes
        return {obj_as_r, [](R*) {}};
    } else {
        auto copy = R::create(exec);
        as<ConvertibleTo<std::decay_t<R>>>(obj)->convert_to(copy);
        return {copy.release(), std::default_delete<R>{}};
    }
}


template <typename R, typename T>
std::shared_ptr<R> copy_and_convert_to_impl(
    std::shared_ptr<const Executor> exec, std::shared_ptr<T> obj)
{
    auto obj_as_r = std::dynamic_pointer_cast<R>(obj);
    if (obj_as_r != nullptr && obj->get_executor() == exec) {
        return obj_as_r;
    } else {
        auto copy = R::create(exec);
        as<ConvertibleTo<std::decay_t<R>>>(obj.get())->convert_to(copy);
        return {std::move(copy)};
    }
}


}  // namespace detail


/**
 * Converts the object to R and places it on Executor exec.
 *
 * If the object is already of the requested type and on the requested executor,
 * the copy and conversion is avoided and a reference to the original object is
 * returned instead.
 *
 * @tparam R  the type to which the object should be converted
 * @tparam T  the type of the input object
 *
 * @param exec  the executor where the result should be placed
 * @param obj  the object that should be converted
 *
 * @return a unique pointer (with dynamically bound deleter) to the converted
 *         object
 */
template <typename R, typename T>
std::unique_ptr<R, std::function<void(R*)>> copy_and_convert_to(
    std::shared_ptr<const Executor> exec, T* obj)
{
    return detail::copy_and_convert_to_impl<R>(std::move(exec), obj);
}


/**
 * @copydoc copy_and_convert_to(std::shared_ptr<const Executor>, T*)
 *
 * @note This is a version of the function which adds the const qualifier to the
 *       result if the input had the same qualifier.
 */
template <typename R, typename T>
std::unique_ptr<const R, std::function<void(const R*)>> copy_and_convert_to(
    std::shared_ptr<const Executor> exec, const T* obj)
{
    return detail::copy_and_convert_to_impl<const R>(std::move(exec), obj);
}


/**
 * Converts the object to R and places it on Executor exec. This is the version
 * that takes in the std::shared_ptr and returns a std::shared_ptr
 *
 * If the object is already of the requested type and on the requested executor,
 * the copy and conversion is avoided and a reference to the original object is
 * returned instead.
 *
 * @tparam R  the type to which the object should be converted
 * @tparam T  the type of the input object
 *
 * @param exec  the executor where the result should be placed
 * @param obj  the object that should be converted
 *
 * @return a shared pointer to the converted
 *         object
 */
template <typename R, typename T>
std::shared_ptr<R> copy_and_convert_to(std::shared_ptr<const Executor> exec,
                                       std::shared_ptr<T> obj)
{
    return detail::copy_and_convert_to_impl<R>(std::move(exec), obj);
}


/**
 * @copydoc copy_and_convert_to(std::shared_ptr<const Executor>,
 * std::shared_ptr<T>)
 *
 * @note This is a version of the function which adds the const qualifier to the
 *       result if the input had the same qualifier.
 */
template <typename R, typename T>
std::shared_ptr<const R> copy_and_convert_to(
    std::shared_ptr<const Executor> exec, std::shared_ptr<const T> obj)
{
    return detail::copy_and_convert_to_impl<const R>(std::move(exec), obj);
}


/**
 * Interface for objects that can be cloned.
 *
 * @note The derived types must also derive from PolymorphicObject.
 */
class Cloneable {
public:
    virtual ~Cloneable() = default;

    [[nodiscard]] std::unique_ptr<Cloneable> clone(
        std::shared_ptr<const Executor> exec) const
    {
        return this->clone_impl(std::move(exec));
    }

    [[nodiscard]] std::unique_ptr<Cloneable> clone() const
    {
        return this->clone_impl();
    }

    Cloneable* copy_from(ptr_param<const Cloneable> other)
    {
        auto copied = this->copy_from_impl(other.get());
        return copied;
    }

    Cloneable* move_from(ptr_param<Cloneable> other)
    {
        auto moved = this->move_from_impl(other.get());
        return moved;
    }

    [[nodiscard]] std::unique_ptr<Cloneable> create_default(
        std::shared_ptr<const Executor> exec) const
    {
        return this->create_default_impl(std::move(exec));
    }

    [[nodiscard]] std::unique_ptr<Cloneable> create_default() const
    {
        return this->create_default_impl();
    }

protected:
    virtual Cloneable* copy_from_impl(const Cloneable* other) = 0;

    virtual Cloneable* move_from_impl(Cloneable* other) = 0;

    [[nodiscard]] virtual std::unique_ptr<Cloneable> clone_impl(
        std::shared_ptr<const Executor> exec) const = 0;

    [[nodiscard]] virtual std::unique_ptr<Cloneable> clone_impl() const = 0;

    [[nodiscard]] virtual std::unique_ptr<Cloneable> create_default_impl()
        const = 0;

    [[nodiscard]] virtual std::unique_ptr<Cloneable> create_default_impl(
        std::shared_ptr<const Executor> exec) const = 0;
};


/**
 * This mixin is used to enable a default Cloneable::clone() implementation and
 * similar for objects that have implemented copy and move constructors.
 *
 * @note The ConcreteType must have public constructors, or this class as a
 *       friend class.
 *
 * @tparam ConcreteType  the concrete type from which the copy_from is being
 *                       enabled [CRTP parameter]
 */
template <typename ConcreteType>
class EnableCloneable : public ConvertibleTo<ConcreteType>, public Cloneable {
public:
    using result_type = ConcreteType;
    using ConvertibleTo<result_type>::convert_to;
    using ConvertibleTo<result_type>::move_to;

    /**
     * Creates a clone of the object.
     *
     * This is the polymorphic equivalent of the _executor copy constructor_
     * `decltype(*this)(exec, this)`.
     *
     * @param exec  the executor where the clone will be created
     *
     * @return A clone of the LinOp.
     */
    [[nodiscard]] std::unique_ptr<ConcreteType> clone(
        std::shared_ptr<const Executor> exec) const
    {
        return as<ConcreteType>(this->clone_impl(std::move(exec)));
    }

    /**
     * Creates a clone of the object.
     *
     * This is a shorthand for clone(std::shared_ptr<const Executor>) that uses
     * the executor of this object to construct the new object.
     *
     * @return A clone of the LinOp.
     */
    [[nodiscard]] std::unique_ptr<ConcreteType> clone() const
    {
        return as<ConcreteType>(this->clone_impl());
    }

    void convert_to(result_type* result) const override { *result = *self(); }

    void move_to(result_type* result) override { *result = std::move(*self()); }

    [[nodiscard]] std::unique_ptr<ConcreteType> create_default() const
    {
        return as<ConcreteType>(this->create_default_impl());
    }

    [[nodiscard]] std::unique_ptr<ConcreteType> create_default(
        std::shared_ptr<const Executor> exec) const
    {
        return as<ConcreteType>(this->create_default_impl(std::move(exec)));
    }

protected:
    Cloneable* copy_from_impl(const Cloneable* other) override
    {
        self()->template log<log::Logger::polymorphic_object_copy_started>(
            self()->get_executor().get(),
            dynamic_cast<const PolymorphicObject*>(other),
            dynamic_cast<const PolymorphicObject*>(this));
        as<ConvertibleTo<ConcreteType>>(other)->convert_to(self());
        self()->template log<log::Logger::polymorphic_object_copy_completed>(
            self()->get_executor().get(),
            dynamic_cast<const PolymorphicObject*>(other),
            dynamic_cast<const PolymorphicObject*>(this));
        return this;
    }

    Cloneable* move_from_impl(Cloneable* other) override
    {
        self()->template log<log::Logger::polymorphic_object_move_started>(
            self()->get_executor().get(),
            dynamic_cast<const PolymorphicObject*>(other),
            dynamic_cast<const PolymorphicObject*>(this));
        as<ConvertibleTo<ConcreteType>>(other)->move_to(self());
        self()->template log<log::Logger::polymorphic_object_move_completed>(
            self()->get_executor().get(),
            dynamic_cast<const PolymorphicObject*>(other),
            dynamic_cast<const PolymorphicObject*>(this));
        return this;
    }

    [[nodiscard]] std::unique_ptr<Cloneable> clone_impl(
        std::shared_ptr<const Executor> exec) const override
    {
        auto new_op = self()->create_default(exec);
        new_op->copy_from(this);
        return new_op;
    }

    [[nodiscard]] std::unique_ptr<Cloneable> clone_impl() const override
    {
        return this->clone_impl(self()->get_executor());
    }

    [[nodiscard]] std::unique_ptr<Cloneable> create_default_impl()
        const override
    {
        return this->create_default_impl(self()->get_executor());
    }

    [[nodiscard]] std::unique_ptr<Cloneable> create_default_impl(
        std::shared_ptr<const Executor> exec) const override
    {
        if constexpr (std::is_base_of_v<
                          experimental::distributed::DistributedBase,
                          ConcreteType>) {
            return std::unique_ptr<ConcreteType>(
                new ConcreteType(std::move(exec), self()->get_communicator()));
        } else {
            return std::unique_ptr<ConcreteType>(
                new ConcreteType(std::move(exec)));
        }
    }

    GKO_ENABLE_SELF(ConcreteType);
};


/**
 * This mixin implements a static `create()` method on `ConcreteType` that
 * dynamically allocates the memory, uses the passed-in arguments to construct
 * the object, and returns an std::unique_ptr to such an object.
 *
 * @tparam ConcreteObject  the concrete type for which `create()` is being
 *                         implemented [CRTP parameter]
 */
template <typename ConcreteType>
class EnableCreateMethod {
public:
    template <typename... Args>
    static std::unique_ptr<ConcreteType> create(Args&&... args)
    {
        return std::unique_ptr<ConcreteType>(
            new ConcreteType(std::forward<Args>(args)...));
    }
};


}  // namespace gko


#endif  // GKO_PUBLIC_CORE_BASE_POLYMORPHIC_OBJECT_HPP_
