Ginkgo: gko::LinOp Class Reference
gko::LinOp Class Reference abstract
Linear Operators
The linear operator (LinOp) is a base class for all linear algebra objects in Ginkgo.
#include <ginkgo/core/base/lin_op.hpp>
Public Member Functions
LinOp * apply (const LinOp *b, LinOp *x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (const LinOp *b, LinOp *x) const
Applies a linear operator to a vector (or a sequence of vectors).
LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Performs the operation x = alpha * op(b) + beta * x.
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
LinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
Adds a new logger to the list of subscribed loggers.
void remove_logger (const Logger *logger) override
Removes a logger from the list of subscribed loggers.
Detailed Description
The linear operator (LinOp) is a base class for all linear algebra objects in Ginkgo.
The main benefit of having a single base class for the entire collection of linear algebra objects (as opposed to having separate hierarchies for matrices, solvers and preconditioners) is the generality it provides.
First, since all subclasses provide a common interface, the library users are exposed to a smaller set of routines. For example, a matrix-vector product, a preconditioner application, or even a system solve are just different terms given to the operation of applying a certain linear operator to a vector. As such, Ginkgo uses the same routine name, LinOp::apply() for each of these operations, where the actual operation performed depends on the type of linear operator involved in the operation.
Second, a common interface often allows for writing more generic code. If a user's routine requires only operations provided by the LinOp interface, the same code can be used for any kind of linear operators, independent of whether these are matrices, solvers or preconditioners. This feature is also extensively used in Ginkgo itself. For example, a preconditioner used inside a Krylov solver is a LinOp. This allows the user to supply a wide variety of preconditioners: either the ones which were designed to be used in this scenario (like ILU or block-Jacobi), a user-supplied matrix which is known to be a good preconditioner for the specific problem, or even another solver (e.g., if constructing a flexible GMRES solver).
A key observation for providing a unified interface for matrices, solvers, and preconditioners is that the most common operation performed on all of them can be expressed as an application of a linear operator to a vector:
the sparse matrix-vector product with a matrix is a linear operator application ;
the application of a preconditioner is a linear operator application , where is an approximation of the original system matrix (thus a preconditioner represents an "approximate inverse" operator).
the system solve can be viewed as linear operator application (it goes without saying that the implementation of linear system solves does not follow this conceptual idea), so a linear system solver can be viewed as a representation of the operator .
Finally, direct manipulation of LinOp objects is rarely required in simple scenarios. As an illustrative example, one could construct a fixed-point iteration routine as follows:
std::unique_ptr<matrix::Dense<>> calculate_fixed_point(
        int iters, const LinOp *L, const matrix::Dense<> *x0
        const matrix::Dense<> *b)
{
    auto x = gko::clone(x0);
    auto tmp = gko::clone(x0);
    auto one = Dense<>::create(L->get_executor(), {1.0,});
    for (int i = 0; i < iters; ++i) {
        L->apply(gko::lend(tmp), gko::lend(x));
        x->add_scaled(gko::lend(one), gko::lend(b));
        tmp->copy_from(gko::lend(x));
    }
    return x;
}
Here, if is a matrix, LinOp::apply() refers to the matrix vector product, and L->apply(a, b) computes . x->add_scaled(one.get(), b.get()) is the axpy vector update .
The interesting part of this example is the apply() routine at line 4 of the function body. Since this routine is part of the LinOp base class, the fixed-point iteration routine can calculate a fixed point not only for matrices, but for any type of linear operator.
Member Function Documentation
LinOp* gko::LinOp::apply (const LinOp * b, LinOp * x)
Applies a linear operator to a vector (or a sequence of vectors).
Performs the operation x = op(b), where op is this linear operator.
Parameters
b the input vector(s) on which the operator is applied
x the output vector(s) where the result is stored
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
const LinOp* gko::LinOp::apply (const LinOp * b, LinOp * x) const
Applies a linear operator to a vector (or a sequence of vectors).
Performs the operation x = op(b), where op is this linear operator.
Parameters
b the input vector(s) on which the operator is applied
x the output vector(s) where the result is stored
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
LinOp* gko::LinOp::apply (const LinOp * alpha, const LinOp * b, const LinOp * beta, LinOp * x)
Performs the operation x = alpha * op(b) + beta * x.
Parameters
alpha scaling of the result of op(b)
b vector(s) on which the operator is applied
beta scaling of the input x
x output vector(s)
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
const LinOp* gko::LinOp::apply (const LinOp * alpha, const LinOp * b, const LinOp * beta, LinOp * x) const
Performs the operation x = alpha * op(b) + beta * x.
Parameters
alpha scaling of the result of op(b)
b vector(s) on which the operator is applied
beta scaling of the input x
x output vector(s)
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
const dim<2>& gko::LinOp::get_size () const noexcept
Returns the size of the operator.
Returns
size of the operator
Referenced by gko::kernels::cuda::ell::advanced_spmv(), gko::matrix::Dense< ValueType >::create_submatrix(), gko::matrix::Dense< ValueType >::create_with_config_of(), gko::Combination< ValueType >::get_operators(), gko::matrix::Csr< ValueType, IndexType >::get_strategy(), gko::log::Convergence< ValueType >::on_criterion_check_completed(), and gko::preconditioner::Jacobi< ValueType, IndexType >::write().
The documentation for this class was generated from the following file:
include/ginkgo/core/base/lin_op.hpp (16519cb)