Ginkgo: gko::Combination< ValueType > Class Template Reference
gko::Combination< ValueType > Class Template Reference
Linear Operators
The Combination class can be used to construct a linear combination of multiple linear operators `c1 * op1 + c2 * op2 + ...
#include <ginkgo/core/base/combination.hpp>
Public Types
using value_type = ValueType
Public Types inherited from gko::EnablePolymorphicAssignment< Combination< ValueType > >
using result_type = Combination< ValueType >
Public Types inherited from gko::ConvertibleTo< Combination< ValueType > >
using result_type = Combination< ValueType >
Public Member Functions
const std::vector< std::shared_ptr< const LinOp > > & get_coefficients () const noexcept
Returns a list of coefficients of the combination.
const std::vector< std::shared_ptr< const LinOp > > & get_operators () const noexcept
Returns a list of operators of the combination.
Public Member Functions inherited from gko::EnableLinOp< Combination< ValueType > >
const Combination< ValueType > * apply (const LinOp *b, LinOp *x) const
Combination< ValueType > * apply (const LinOp *b, LinOp *x)
const Combination< ValueType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Combination< ValueType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< Combination< ValueType >, LinOp >
std::unique_ptr< Combination< ValueType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Combination< ValueType > > create_default () const
std::unique_ptr< Combination< ValueType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Combination< ValueType > > clone () const
Combination< ValueType > * copy_from (const PolymorphicObject *other)
Combination< ValueType > * copy_from (std::unique_ptr< PolymorphicObject > other)
Combination< ValueType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (const LinOp *b, LinOp *x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (const LinOp *b, LinOp *x) const
Applies a linear operator to a vector (or a sequence of vectors).
LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Performs the operation x = alpha * op(b) + beta * x.
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
LinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
Adds a new logger to the list of subscribed loggers.
void remove_logger (const Logger *logger) override
Removes a logger from the list of subscribed loggers.
Public Member Functions inherited from gko::EnablePolymorphicAssignment< Combination< ValueType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Friends
class EnablePolymorphicObject< Combination, LinOp >
class EnableCreateMethod< Combination >
Additional Inherited Members
Static Public Member Functions inherited from gko::EnableCreateMethod< Combination< ValueType > >
static std::unique_ptr< Combination< ValueType > > create (Args &&...args)
Detailed Description
template<typename ValueType = default_precision>
class gko::Combination< ValueType >
The Combination class can be used to construct a linear combination of multiple linear operators `c1 * op1 + c2 * op2 + ...
ck * opk`.
Template Parameters
ValueType precision of input and result vectors
Member Function Documentation
template<typename ValueType = default_precision> const std::vector<std::shared_ptr<const LinOp> >& gko::Combination< ValueType >::get_coefficients () const noexcept
Returns a list of coefficients of the combination.
Returns
a list of coefficients
template<typename ValueType = default_precision> const std::vector<std::shared_ptr<const LinOp> >& gko::Combination< ValueType >::get_operators () const noexcept
Returns a list of operators of the combination.
Returns
a list of operators
References gko::LinOp::get_size(), gko::one(), and gko::zero().
The documentation for this class was generated from the following files:
include/ginkgo/core/base/combination.hpp (16519cb)
core/base/combination.cpp (fc51980)