Ginkgo: gko::kernels::cuda Namespace Reference
gko::kernels::cuda Namespace Reference
The CUDA namespace.
Namespaces
bicgstab
The BICGSTAB solver.
cg
The CG solver.
cgs
The CGS solver.
coo
The Coordinate matrix format.
csr
The Compressed sparse row matrix format.
cublas
The CUBLAS namespace.
cusparse
The CUSPARSE namespace.
dense
The Dense matrix format.
ell
The ELL matrix format.
fcg
The FCG solver.
gmres
The GMRES solver.
hybrid
The Hybrid matrix format.
residual_norm_reduction
The Residual norm reduction stopping criterion.
sellp
The SELL-P format.
set_all_statuses
Setting of all statuses.
thread
The CUDA thread namespace.
Classes
struct cuda_config
class UninitializedArray
Stores an array with uninitialized contents.
Typedefs
using DefaultExecutor = CudaExecutor
template<typename T >
using cuda_type = typename detail::cuda_type_impl< T >::type
This is an alias for CUDA's equivalent of T.
template<typename T >
using culibs_type = typename detail::culibs_type_impl< T >::type
This is an alias for equivalent of type T used in CUDA libraries (cuBLAS, cuSPARSE, etc.).
using compiled_kernels = syn::value_list< int, 1, 13, 16, 32 >
A compile-time list of block sizes for which dedicated generate and apply kernels should be compiled.
Enumerations
enum postprocess_transformation { and_return, and_transpose }
Functions
template<typename T >
xstd::enable_if_t< std::is_pointer< T >::value||std::is_reference< T >::value, cuda_type< T > > as_cuda_type (T val)
Reinterprets the passed in value as a CUDA type.
template<typename T >
xstd::enable_if_t< !std::is_pointer< T >::value &&!std::is_reference< T >::value, cuda_type< T > > as_cuda_type (T val)
Reinterprets the passed in value as a CUDA type.
template<typename T >
culibs_type< T > as_culibs_type (T val)
Reinterprets the passed in value as an equivalent type used by the CUDA libraries.
template<typename T >
__forceinline__ __device__ void atomic_add (T *, T)
__forceinline__ __device__ void atomic_add (int *__restrict__ addr, int val)
__forceinline__ __device__ void atomic_add (unsigned int *__restrict__ addr, unsigned int val)
__forceinline__ __device__ void atomic_add (unsigned long long int *__restrict__ addr, unsigned long long int val)
__forceinline__ __device__ void atomic_add (float *__restrict__ addr, float val)
__forceinline__ __device__ void atomic_add (double *__restrict__ addr, double val)
__forceinline__ __device__ void atomic_add (thrust::complex< float > *__restrict__ address, thrust::complex< float > val)
__forceinline__ __device__ void atomic_add (thrust::complex< double > *__restrict__ address, thrust::complex< double > val)
template<typename Group , typename ValueType , typename Operator , typename = xstd::enable_if_t<group::is_communicator_group<Group>::value>>
__device__ __forceinline__ ValueType reduce (const Group &group, ValueType local_data, Operator reduce_op=Operator{})
template<typename Group , typename ValueType , typename = xstd::enable_if_t<group::is_communicator_group<Group>::value>>
__device__ __forceinline__ int choose_pivot (const Group &group, ValueType local_data, bool is_pivoted)
template<typename Group , typename ValueType , typename Operator , typename = xstd::enable_if_t<group::is_synchronizable_group<Group>::value>>
__device__ void reduce (const Group &__restrict__ group, ValueType *__restrict__ data, Operator reduce_op=Operator{})
template<int max_problem_size, typename Group , typename ValueType , typename = xstd::enable_if_t<group::is_communicator_group<Group>::value>>
__device__ __forceinline__ void apply_gauss_jordan_transform (const Group &__restrict__ group, int32 key_row, int32 key_col, ValueType *__restrict__ row, bool &__restrict__ status)
template<int max_problem_size, typename Group , typename ValueType , typename = xstd::enable_if_t<group::is_communicator_group<Group>::value>>
__device__ __forceinline__ bool invert_block (const Group &__restrict__ group, uint32 problem_size, ValueType *__restrict__ row, uint32 &__restrict__ perm, uint32 &__restrict__ trans_perm)
template<postprocess_transformation mod, typename T1 , typename T2 , typename T3 >
__host__ __device__ __forceinline__ auto get_row_major_index (T1 row, T2 col, T3 stride) -> typename std::enable_if< mod!=and_transpose, typename std::decay< decltype(row *stride+col)>::type >::type
template<int max_problem_size, postprocess_transformation mod = and_return, typename Group , typename SourceValueType , typename ResultValueType , typename = xstd::enable_if_t<group::is_communicator_group<Group>::value>>
__device__ __forceinline__ void copy_matrix (const Group &__restrict__ group, uint32 problem_size, const SourceValueType *__restrict__ source_row, uint32 increment, uint32 row_perm, uint32 col_perm, ResultValueType *__restrict__ destination, size_type stride)
template<int max_problem_size, typename Group , typename MatrixValueType , typename VectorValueType , typename = xstd::enable_if_t<group::is_communicator_group<Group>::value>>
__device__ __forceinline__ void multiply_transposed_vec (const Group &__restrict__ group, uint32 problem_size, const VectorValueType &__restrict__ vec, const MatrixValueType *__restrict__ mtx_row, uint32 mtx_increment, VectorValueType *__restrict__ res, uint32 res_increment)
template<int max_problem_size, typename Group , typename MatrixValueType , typename VectorValueType , typename = xstd::enable_if_t<group::is_communicator_group<Group>::value>>
__device__ __forceinline__ void multiply_vec (const Group &__restrict__ group, uint32 problem_size, const VectorValueType &__restrict__ vec, const MatrixValueType *__restrict__ mtx_row, uint32 mtx_increment, VectorValueType *__restrict__ res, uint32 res_increment)
template<int max_problem_size, typename Group , typename ValueType , typename = xstd::enable_if_t<group::is_communicator_group<Group>::value>>
__device__ __forceinline__ remove_complex< ValueType > compute_infinity_norm (const Group &group, uint32 num_rows, uint32 num_cols, const ValueType *row)
template<typename ValueType >
void zero_array (size_type n, ValueType *array)
Zeroes an array allocated on a CUDA device.
template void zero_array< float > (size_type n, float *array)
template void zero_array< double > (size_type n, double *array)
Variables
constexpr int default_block_size = 512
Detailed Description
The CUDA namespace.
cuda namespace.
Typedef Documentation
template<typename T > using gko::kernels::cuda::cuda_type = typedef typename detail::cuda_type_impl<T>::type
This is an alias for CUDA's equivalent of T.
Template Parameters
T a type
template<typename T > using gko::kernels::cuda::culibs_type = typedef typename detail::culibs_type_impl<T>::type
This is an alias for equivalent of type T used in CUDA libraries (cuBLAS, cuSPARSE, etc.).
Template Parameters
T a type
Function Documentation
template<typename T > xstd::enable_if_t< std::is_pointer<T>::value || std::is_reference<T>::value, cuda_type<T> > gko::kernels::cuda::as_cuda_type (T val)
Reinterprets the passed in value as a CUDA type.
Parameters
val the value to reinterpret
Returns
val reinterpreted to CUDA type
Referenced by gko::kernels::cuda::ell::advanced_spmv().
template<typename T > xstd::enable_if_t< !std::is_pointer<T>::value && !std::is_reference<T>::value, cuda_type<T> > gko::kernels::cuda::as_cuda_type (T val)
Reinterprets the passed in value as a CUDA type.
Parameters
val the value to reinterpret
Returns
val reinterpreted to CUDA type
template<typename T > culibs_type<T> gko::kernels::cuda::as_culibs_type (T val)
Reinterprets the passed in value as an equivalent type used by the CUDA libraries.
Parameters
val the value to reinterpret
Returns
val reinterpreted to type used by CUDA libraries
template<typename ValueType > void gko::kernels::cuda::zero_array (size_type n, ValueType * array)
Zeroes an array allocated on a CUDA device.
Template Parameters
ValueType the type of the array's elements
Parameters
n the size of the array
array the array to fill with zeros
References gko::ceildiv().
Referenced by gko::kernels::cuda::ell::spmv().