Ginkgo: gko::kernels::cuda::ell Namespace Reference
gko::kernels::cuda::ell Namespace Reference
The ELL matrix format.
Typedefs
using compiled_kernels = syn::value_list< int, 0, 1, 2, 4, 8, 16, 32 >
A compile-time list of sub-warp sizes for which the spmv kernels should be compiled.
Functions
template<typename ValueType , typename IndexType >
void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< ValueType, IndexType > *a, const matrix::Dense< ValueType > *b, matrix::Dense< ValueType > *c)
template<typename ValueType , typename IndexType >
void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< ValueType > *alpha, const matrix::Ell< ValueType, IndexType > *a, const matrix::Dense< ValueType > *b, const matrix::Dense< ValueType > *beta, matrix::Dense< ValueType > *c)
template<typename ValueType , typename IndexType >
void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< ValueType > *result, const matrix::Ell< ValueType, IndexType > *source)
template void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< float, int32 > *a, const matrix::Dense< float > *b, matrix::Dense< float > *c)
template void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< double, int32 > *a, const matrix::Dense< double > *b, matrix::Dense< double > *c)
template void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< std::complex< float >, int32 > *a, const matrix::Dense< std::complex< float > > *b, matrix::Dense< std::complex< float > > *c)
template void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< std::complex< double >, int32 > *a, const matrix::Dense< std::complex< double > > *b, matrix::Dense< std::complex< double > > *c)
template void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< float, int64 > *a, const matrix::Dense< float > *b, matrix::Dense< float > *c)
template void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< double, int64 > *a, const matrix::Dense< double > *b, matrix::Dense< double > *c)
template void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< std::complex< float >, int64 > *a, const matrix::Dense< std::complex< float > > *b, matrix::Dense< std::complex< float > > *c)
template void spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< std::complex< double >, int64 > *a, const matrix::Dense< std::complex< double > > *b, matrix::Dense< std::complex< double > > *c)
template void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< float > *alpha, const matrix::Ell< float, int32 > *a, const matrix::Dense< float > *b, const matrix::Dense< float > *beta, matrix::Dense< float > *c)
template void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< double > *alpha, const matrix::Ell< double, int32 > *a, const matrix::Dense< double > *b, const matrix::Dense< double > *beta, matrix::Dense< double > *c)
template void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< std::complex< float > > *alpha, const matrix::Ell< std::complex< float >, int32 > *a, const matrix::Dense< std::complex< float > > *b, const matrix::Dense< std::complex< float > > *beta, matrix::Dense< std::complex< float > > *c)
template void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< std::complex< double > > *alpha, const matrix::Ell< std::complex< double >, int32 > *a, const matrix::Dense< std::complex< double > > *b, const matrix::Dense< std::complex< double > > *beta, matrix::Dense< std::complex< double > > *c)
template void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< float > *alpha, const matrix::Ell< float, int64 > *a, const matrix::Dense< float > *b, const matrix::Dense< float > *beta, matrix::Dense< float > *c)
template void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< double > *alpha, const matrix::Ell< double, int64 > *a, const matrix::Dense< double > *b, const matrix::Dense< double > *beta, matrix::Dense< double > *c)
template void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< std::complex< float > > *alpha, const matrix::Ell< std::complex< float >, int64 > *a, const matrix::Dense< std::complex< float > > *b, const matrix::Dense< std::complex< float > > *beta, matrix::Dense< std::complex< float > > *c)
template void advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< std::complex< double > > *alpha, const matrix::Ell< std::complex< double >, int64 > *a, const matrix::Dense< std::complex< double > > *b, const matrix::Dense< std::complex< double > > *beta, matrix::Dense< std::complex< double > > *c)
template void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< float > *result, const matrix::Ell< float, int32 > *source)
template void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< double > *result, const matrix::Ell< double, int32 > *source)
template void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< std::complex< float > > *result, const matrix::Ell< std::complex< float >, int32 > *source)
template void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< std::complex< double > > *result, const matrix::Ell< std::complex< double >, int32 > *source)
template void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< float > *result, const matrix::Ell< float, int64 > *source)
template void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< double > *result, const matrix::Ell< double, int64 > *source)
template void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< std::complex< float > > *result, const matrix::Ell< std::complex< float >, int64 > *source)
template void convert_to_dense (std::shared_ptr< const DefaultExecutor > exec, matrix::Dense< std::complex< double > > *result, const matrix::Ell< std::complex< double >, int64 > *source)
Variables
constexpr int default_block_size = 512
constexpr int num_threads_per_core = 4
num_threads_per_core is the oversubscribing parameter.
constexpr double ratio = 1e-2
ratio is the parameter to decide when to use threads to do reduction on each row.
Detailed Description
The ELL matrix format.
Typedef Documentation
using gko::kernels::cuda::ell::compiled_kernels = typedef syn::value_list<int, 0, 1, 2, 4, 8, 16, 32>
A compile-time list of sub-warp sizes for which the spmv kernels should be compiled.
0 is a special case where it uses a sub-warp size of 32 in combination with atomic_adds.
Function Documentation
template<typename ValueType , typename IndexType > void gko::kernels::cuda::ell::advanced_spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Dense< ValueType > * alpha, const matrix::Ell< ValueType, IndexType > * a, const matrix::Dense< ValueType > * b, const matrix::Dense< ValueType > * beta, matrix::Dense< ValueType > * c)
info is the parameter for selecting the cuda kernel. for info == 0, it uses the kernel by 32 threads with atomic operation for other value, it uses the kernel without atomic_add
info is the parameter for selecting the cuda kernel. for info == 0, it uses the kernel by 32 threads with atomic operation for other value, it uses the kernel without atomic_add
References gko::kernels::cuda::as_cuda_type(), gko::ceildiv(), gko::matrix::Ell< ValueType, IndexType >::get_const_col_idxs(), gko::matrix::Ell< ValueType, IndexType >::get_const_values(), gko::matrix::Ell< ValueType, IndexType >::get_num_stored_elements_per_row(), gko::LinOp::get_size(), gko::matrix::Ell< ValueType, IndexType >::get_stride(), gko::matrix::Dense< ValueType >::get_stride(), gko::matrix::Dense< ValueType >::get_values(), gko::kernels::cuda::cuda_config::max_block_size, and gko::kernels::cuda::cuda_config::warp_size.
template<typename ValueType , typename IndexType > void gko::kernels::cuda::ell::spmv (std::shared_ptr< const DefaultExecutor > exec, const matrix::Ell< ValueType, IndexType > * a, const matrix::Dense< ValueType > * b, matrix::Dense< ValueType > * c)
info is the parameter for selecting the cuda kernel. for info == 0, it uses the kernel by 32 threads with atomic operation for other value, it uses the kernel without atomic_add
info is the parameter for selecting the cuda kernel. for info == 0, it uses the kernel by 32 threads with atomic operation for other value, it uses the kernel without atomic_add
References gko::matrix::Dense< ValueType >::get_num_stored_elements(), gko::matrix::Dense< ValueType >::get_values(), and gko::kernels::cuda::zero_array().
Variable Documentation
constexpr int gko::kernels::cuda::ell::num_threads_per_core = 4
num_threads_per_core is the oversubscribing parameter.
There are num_threads_per_core threads assigned to each physical core.
constexpr double gko::kernels::cuda::ell::ratio = 1e-2
ratio is the parameter to decide when to use threads to do reduction on each row.
(#cols/#rows > ratio)