build/cuda110/nompi/gcc/cuda/release/shared:
  extends:
    - .build_and_test_template
    - .default_variables
    - .quick_test_condition
    - .use_gko_cuda110-mvapich-gnu9-llvm9
  variables:
    BUILD_OMP: "ON"
    BUILD_CUDA: "ON"
    BUILD_MPI: "OFF"
    BUILD_TYPE: "Release"
    FAST_TESTS: "ON"
    # disable spurious unused argument warning
    # this is seemingly broken with CUDA 11
    # EXTRA_CMAKE_FLAGS: "-DCMAKE_CUDA_FLAGS=-diag-suppress=177"
  comments:
    test 123
    is comments allowed by gitlab?

build/nvhpc227/cuda117/nompi/nvcpp/debug/shared:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko_nvhpc227-cuda117-openmpi-gnu11-llvm14
  variables:
    CXX_COMPILER: "nvc++"
    BUILD_OMP: "ON"
    BUILD_CUDA: "ON"
    BUILD_MPI: "OFF"
    BUILD_TYPE: "Debug"
    FAST_TESTS: "ON"
    CXX_FLAGS: "--diag_suppress=useless_using_declaration,declared_but_not_referenced"
    EXTRA_CMAKE_FLAGS: "-DCMAKE_CUDA_FLAGS=-diag-suppress=177"
  # `--diag_suppress=useless_using_declaration,declared_but_not_referenced` disables common gflags warning
  # `-diag-suppress=188` disables spurious unused argument warning in CUDA

build/cuda118/nompi/gcc/cuda/debug/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-nvidia
  variables:
    BUILD_CUDA: "ON"
    BUILD_HWLOC: "OFF"
    ENABLE_HALF: "ON"
    BUILD_TYPE: "Debug"
    MODULE_LOAD: "cmake/3.18.6 cuda/11.8.0 gcc/7.5.0"

build/cuda120/openmpi/gcc/cuda/release/static:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-nvidia
  variables:
    BUILD_CUDA: "ON"
    BUILD_HWLOC: "OFF"
    ENABLE_HALF: "ON"
    BUILD_MPI: "ON"
    BUILD_SHARED_LIBS: "OFF"
    BUILD_TYPE: "Release"
    MODULE_LOAD: "cmake/3.18.6 cuda/12.0.1 gcc/12.4.0 openmpi/4.1.8"

build/cuda122/openmpi/gcc/cuda/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-nvidia
  variables:
    BUILD_CUDA: "ON"
    BUILD_HWLOC: "OFF"
    ENABLE_HALF: "ON"
    BUILD_TYPE: "Release"
    MODULE_LOAD: "cmake/3.20.6 cuda/12.2.2 gcc/12.4.0 openmpi/5.0.7"

build/cuda124/mpich/gcc/cuda/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-nvidia
  variables:
    BUILD_CUDA: "ON"
    BUILD_HWLOC: "OFF"
    BUILD_MPI: "ON"
    ENABLE_HALF: "ON"
    ENABLE_BFLOAT16: "ON"
    BUILD_TYPE: "Release"
    MODULE_LOAD: "cmake/3.30.8 cuda/12.6.3 gcc/13.3.0 mpich"

build/cuda126/nompi/gcc/cuda/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-nvidia
  variables:
    BUILD_CUDA: "ON"
    BUILD_HWLOC: "OFF"
    ENABLE_HALF: "ON"
    ENABLE_BFLOAT16: "ON"
    BUILD_TYPE: "Release"
    MODULE_LOAD: "cmake/3.30.8 cuda/12.6.3 gcc/13.3.0"

build/cuda130/nompi/gcc/cuda/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-nvidia
  variables:
    BUILD_CUDA: "ON"
    BUILD_HWLOC: "OFF"
    ENABLE_HALF: "ON"
    ENABLE_BFLOAT16: "ON"
    BUILD_TYPE: "Release"
    MODULE_LOAD: "cmake/3.30.8 cuda/13.0.2 gcc/14.3.0"

build/cuda131/nompi/gcc/cuda/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-nvidia
  variables:
    BUILD_CUDA: "ON"
    BUILD_HWLOC: "OFF"
    ENABLE_HALF: "ON"
    ENABLE_BFLOAT16: "ON"
    BUILD_TYPE: "Release"
    MODULE_LOAD: "cmake/3.30.8 cuda/13.1.1 gcc/14.3.0"

build/amd/openmpi/gcc/rocm620/debug/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .quick_test_condition
    - .use_tum-amd
  variables:
    BUILD_HIP: "ON"
    BUILD_HWLOC: "OFF"
    BUILD_MPI: "ON"
    BUILD_OMP: "ON"
    BUILD_TYPE: "Debug"
    BUILD_SHARED_LIBS: "ON"
    MODULE_LOAD: "cmake/3.24.4 rocm/6.2.0 gcc/13.3.0 openmpi/5.0.7"

build/amd/openmpi/gcc/rocm634_wo_omp/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-amd
  variables:
    BUILD_HIP: "ON"
    BUILD_HWLOC: "OFF"
    BUILD_MPI: "ON"
    BUILD_TYPE: "Release"
    MODULE_LOAD: "cmake/3.29.6 rocm/6.3.4 gcc/13.3.0 openmpi/5.0.7"
  # MI50 is officially supported by ROCm < 6.4.0

build/amd/nompi/gcc/rocm644/debug/static:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-amd-mi210
  variables:
    BUILD_HIP: "ON"
    BUILD_HWLOC: "OFF"
    BUILD_MPI: "OFF"
    BUILD_OMP: "OFF"
    BUILD_TYPE: "Debug"
    BUILD_SHARED_LIBS: "OFF"
    MODULE_LOAD: "cmake/3.29.6 rocm/6.4.4 gcc/14.3.0"
  # MI50 is not officially supported by ROCm >= 6.4.0

build/amd/nompi/gcc/rocm710/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-amd-mi210
  variables:
    BUILD_HIP: "ON"
    BUILD_HWLOC: "OFF"
    BUILD_MPI: "OFF"
    BUILD_OMP: "OFF"
    BUILD_TYPE: "Release"
    MODULE_LOAD: "cmake/3.29.6 rocm/7.1.0 gcc/14.3.0"

build/amd/nompi/gcc/rocm720/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-amd
  variables:
    BUILD_HIP: "ON"
    BUILD_OMP: "OFF"
    BUILD_HWLOC: "OFF"
    BUILD_TYPE: "Release"
    ENABLE_BFLOAT16: "OFF"
    ENABLE_HALF: "OFF"
    MODULE_LOAD: "cmake/3.25.3 rocm/7.2.0 gcc/12.4.0"

build/nocuda/nompi/gcc/core/debug/static:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-nocuda-nompi-gnu9-llvm8
  variables:
    BUILD_TYPE: "Debug"
    FAST_TESTS: "ON"
    BUILD_SHARED_LIBS: "OFF"
    BUILD_HWLOC: "OFF"

build/nocuda/nompi/clang/core/release/shared:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-nocuda-nompi-gnu9-llvm8
  variables:
    CXX_COMPILER: "clang++"
    BUILD_TYPE: "Release"
    ENABLE_HALF: "OFF"
    ENABLE_BFLOAT16: "ON"

build/nocuda/nompi/gcc/omp/release/shared:
  extends:
    - .build_and_test_template
    - .default_variables
    - .quick_test_condition
    - .use_gko-nocuda-nompi-gnu9-llvm8
  variables:
    BUILD_OMP: "ON"
    BUILD_TYPE: "Release"
    ENABLE_HALF: "ON"
    ENABLE_BFLOAT16: "ON"

build/nocuda/openmpi/clang/omp/debug/static:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-nocuda-openmpi-gnu9-llvm8
  variables:
    CXX_COMPILER: "clang++"
    BUILD_OMP: "ON"
    MPI_AS_ROOT: "ON"
    BUILD_MPI: "ON"
    BUILD_TYPE: "Debug"
    FAST_TESTS: "ON"
    BUILD_SHARED_LIBS: "OFF"

build/nocuda/openmpi/clang/omp/glibcxx-debug-release/shared:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-nocuda-nompi-gnu9-llvm8
  variables:
    CXX_COMPILER: "clang++"
    BUILD_OMP: "ON"
    MPI_AS_ROOT: "ON"
    BUILD_MPI: "ON"
    CXX_FLAGS: "-Wpedantic -D_GLIBCXX_DEBUG=1"
    BUILD_TYPE: "Release"
  # We use Release here bacause glibcxx tests are prohibitively slow in Debug

build/nocuda/nompi/gcc/omp/release/static:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-nocuda-nompi-gnu9-llvm8
  variables:
    BUILD_OMP: "ON"
    BUILD_TYPE: "Release"
    BUILD_SHARED_LIBS: "OFF"
    ENABLE_HALF: "OFF"
    ENABLE_BFLOAT16: "ON"

build/nocuda-nomixed/nompi/clang/omp/release/static:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-nocuda-nompi-gnu9-llvm8
  variables:
    CXX_COMPILER: "clang++"
    BUILD_OMP: "ON"
    BUILD_TYPE: "Release"
    BUILD_SHARED_LIBS: "OFF"
    MIXED_PRECISION: "OFF"

build/nocuda-nomixed/openmpi/gcc/omp/release/shared:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-nocuda-nompi-gnu9-llvm8
  variables:
    BUILD_MPI: "ON"
    MPI_AS_ROOT: "ON"
    BUILD_OMP: "ON"
    BUILD_TYPE: "Release"
    MIXED_PRECISION: "OFF"

build/nocuda-nomixed/nompi/clang/omp/debug/static:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-nocuda-nompi-gnu9-llvm8
  variables:
    CXX_COMPILER: "clang++"
    BUILD_OMP: "ON"
    BUILD_TYPE: "Debug"
    BUILD_SHARED_LIBS: "OFF"
    MIXED_PRECISION: "OFF"

build/nogpu/nompi/gcc/omp/debug/static:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-cpu
  variables:
    BUILD_OMP: "ON"
    BUILD_TYPE: "Debug"
    BUILD_SHARED_LIBS: "OFF"
    MIXED_PRECISION: "OFF"
    BUILD_HWLOC: "OFF"
    MODULE_LOAD: "cmake/3.18.6 gcc/7.5.0"

build/nogpu/nompi/gcc/omp/release/static:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-cpu
  variables:
    BUILD_OMP: "ON"
    BUILD_TYPE: "Release"
    BUILD_SHARED_LIBS: "OFF"
    ENABLE_HALF: "ON"
    ENABLE_BFLOAT16: "ON"
    BUILD_HWLOC: "OFF"
    MODULE_LOAD: "cmake/3.18.6 gcc/9.5.0"

build/nogpu/nompi/gcc/noomp/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-cpu
  variables:
    BUILD_TYPE: "Release"
    BUILD_HWLOC: "OFF"
    MODULE_LOAD: "cmake/3.18.6 gcc/9.5.0"

build/nogpu/nompi/gcc12/noomp/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-cpu
  variables:
    BUILD_TYPE: "Release"
    BUILD_HWLOC: "OFF"
    MODULE_LOAD: "cmake/3.18.6 gcc/12.4.0"

build/nogpu/mpi/gcc13/noomp/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .quick_test_condition
    - .use_tum-cpu
  variables:
    BUILD_TYPE: "Release"
    BUILD_HWLOC: "OFF"
    BUILD_MPI: "ON"
    MODULE_LOAD: "cmake/3.18.6 gcc/13.3.0 openmpi"

build/icpx20231/gpu/release/shared:
  extends:
    - .build_and_test_template
    - .default_variables
    - .quick_test_condition
    - .use_gko-oneapi20231-gpu
  variables:
    CXX_COMPILER: "icpx"
    CXX_FLAGS: "-Wpedantic -ffp-model=precise"
    BUILD_SYCL: "ON"
    BUILD_TYPE: "Release"
    BUILD_SHARED_LIBS: "ON"
    DPCPP_SINGLE_MODE: "ON"
    ONEAPI_DEVICE_SELECTOR: "opencl:gpu"
    BUILD_HWLOC: "OFF"

build/dpcpp20231/gpu/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-intel-fp32
  variables:
    CXX_COMPILER: "dpcpp"
    CXX_FLAGS: "-Wpedantic -ffp-model=precise"
    BUILD_SYCL: "ON"
    BUILD_TYPE: "Release"
    BUILD_SHARED_LIBS: "ON"
    DPCPP_SINGLE_MODE: "ON"
    MODULE_LOAD: "cmake/3.21.7 intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 intel-oneapi-tbb/2021.9.0 intel-oneapi-mkl/2023.1.0"
    ONEAPI_DEVICE_SELECTOR: "opencl:gpu"
    BUILD_HWLOC: "OFF"

build/icpx202402/gpu/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-intel
  variables:
    CXX_COMPILER: "icpx"
    CXX_FLAGS: "-Wpedantic -ffp-model=precise -Wno-deprecated-declarations"
    BUILD_SYCL: "ON"
    BUILD_HWLOC: "OFF"
    BUILD_TYPE: "Release"
    ENABLE_HALF: "OFF"
    ENABLE_BFLOAT16: "OFF"
    ONEAPI_DEVICE_SELECTOR: "opencl:gpu"
    MODULE_LOAD: "cmake/3.21.7 intel-oneapi-compilers/2024.0.2 intel-oneapi-dpl/2022.3.0 intel-oneapi-tbb/2021.11.0 intel-oneapi-mkl/2024.0.0"

build/icpx202421/gpu/release/shared:
  extends:
    - .build_and_test_tum_template
    - .default_variables
    - .full_test_condition
    - .use_tum-intel
  variables:
    CXX_COMPILER: "icpx"
    CXX_FLAGS: "-Wpedantic -ffp-model=precise -Wno-deprecated-declarations"
    BUILD_SYCL: "ON"
    BUILD_OMP: "ON"
    BUILD_HWLOC: "OFF"
    BUILD_TYPE: "Release"
    ENABLE_HALF: "ON"
    ENABLE_BFLOAT16: "ON"
    ONEAPI_DEVICE_SELECTOR: "level_zero:gpu"
    MODULE_LOAD: "cmake/3.28.6 intel-oneapi-compilers/2024.2.1 intel-oneapi-dpl/2022.6.1 intel-oneapi-tbb/2021.13.1 intel-oneapi-mkl/2024.2.1"

build/dpcpp/gpu/release/shared:
  extends:
    - .build_and_test_template
    - .default_variables
    - .full_test_condition
    - .use_gko-oneapi-gpu
  variables:
    CXX_COMPILER: "dpcpp"
    CXX_FLAGS: "-Wpedantic -ffp-model=precise"
    BUILD_SYCL: "ON"
    BUILD_TYPE: "Release"
    BUILD_SHARED_LIBS: "ON"
    DPCPP_SINGLE_MODE: "ON"
    ONEAPI_DEVICE_SELECTOR: "*:gpu"
    BUILD_HWLOC: "OFF"
  # This gives two available backends of GPU on tests
