Ginkgo: gko::matrix::SparsityCsr< ValueType, IndexType > Class Template Reference
gko::matrix::SparsityCsr< ValueType, IndexType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | Linear Operators
SparsityCsr is a matrix format which stores only the sparsity pattern of a sparse matrix by compressing each row of the matrix (compressed sparse row format).
#include <ginkgo/core/matrix/sparsity_csr.hpp>
Public Types
using value_type = ValueType
using index_type = IndexType
using mat_data = matrix_data< ValueType, IndexType >
Public Types inherited from gko::EnablePolymorphicAssignment< SparsityCsr< ValueType, IndexType > >
using result_type = SparsityCsr< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< SparsityCsr< ValueType, IndexType > >
using result_type = SparsityCsr< ValueType, IndexType >
Public Member Functions
void read (const mat_data &data) override
Reads a matrix from a matrix_data structure.
void write (mat_data &data) const override
Writes a matrix to a matrix_data structure.
std::unique_ptr< LinOp > transpose () const override
Returns a LinOp representing the transpose of the Transposable object.
std::unique_ptr< LinOp > conj_transpose () const override
Returns a LinOp representing the conjugate transpose of the Transposable object.
std::unique_ptr< SparsityCsr > to_adjacency_matrix () const
Transforms the sparsity matrix to an adjacency matrix.
void sort_by_column_index ()
Sorts each row by column index.
bool is_sorted_by_column_index () const
index_type * get_col_idxs () noexcept
Returns the column indices of the matrix.
const index_type * get_const_col_idxs () const noexcept
Returns the column indices of the matrix.
index_type * get_row_ptrs () noexcept
Returns the row pointers of the matrix.
const index_type * get_const_row_ptrs () const noexcept
Returns the row pointers of the matrix.
value_type * get_value () noexcept
Returns the value stored in the matrix.
const value_type * get_const_value () const noexcept
Returns the value stored in the matrix.
size_type get_num_nonzeros () const noexcept
Returns the number of elements explicitly stored in the matrix.
Public Member Functions inherited from gko::EnableLinOp< SparsityCsr< ValueType, IndexType > >
const SparsityCsr< ValueType, IndexType > * apply (const LinOp *b, LinOp *x) const
SparsityCsr< ValueType, IndexType > * apply (const LinOp *b, LinOp *x)
const SparsityCsr< ValueType, IndexType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
SparsityCsr< ValueType, IndexType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< SparsityCsr< ValueType, IndexType >, LinOp >
std::unique_ptr< SparsityCsr< ValueType, IndexType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< SparsityCsr< ValueType, IndexType > > create_default () const
std::unique_ptr< SparsityCsr< ValueType, IndexType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< SparsityCsr< ValueType, IndexType > > clone () const
SparsityCsr< ValueType, IndexType > * copy_from (const PolymorphicObject *other)
SparsityCsr< ValueType, IndexType > * copy_from (std::unique_ptr< PolymorphicObject > other)
SparsityCsr< ValueType, IndexType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (const LinOp *b, LinOp *x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (const LinOp *b, LinOp *x) const
Applies a linear operator to a vector (or a sequence of vectors).
LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Performs the operation x = alpha * op(b) + beta * x.
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
LinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
Adds a new logger to the list of subscribed loggers.
void remove_logger (const Logger *logger) override
Removes a logger from the list of subscribed loggers.
Public Member Functions inherited from gko::EnablePolymorphicAssignment< SparsityCsr< ValueType, IndexType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Friends
class EnableCreateMethod< SparsityCsr >
class EnablePolymorphicObject< SparsityCsr, LinOp >
class Csr< ValueType, IndexType >
Additional Inherited Members
Static Public Member Functions inherited from gko::EnableCreateMethod< SparsityCsr< ValueType, IndexType > >
static std::unique_ptr< SparsityCsr< ValueType, IndexType > > create (Args &&... args)
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::SparsityCsr< ValueType, IndexType >
SparsityCsr is a matrix format which stores only the sparsity pattern of a sparse matrix by compressing each row of the matrix (compressed sparse row format).
The values of the nonzero elements are stored as a value array of length 1. All the values in the matrix are equal to this value. By default, this value is set to 1.0. A row pointer array also stores the linearized starting index of each row. An additional column index array is used to identify the column where a nonzero is present.
Template Parameters
ValueType precision of vectors in apply
IndexType precision of matrix indexes
Member Function Documentation
conj_transpose()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<LinOp> gko::matrix::SparsityCsr< ValueType, IndexType >::conj_transpose () const override virtual
Returns a LinOp representing the conjugate transpose of the Transposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::Transposable.
get_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_col_idxs () inline noexcept
Returns the column indices of the matrix.
Returns
the column indices of the matrix.
References gko::Array< ValueType >::get_data().
get_const_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_col_idxs () const inline noexcept
Returns the column indices of the matrix.
Returns
the column indices of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
get_const_row_ptrs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_row_ptrs () const inline noexcept
Returns the row pointers of the matrix.
Returns
the row pointers of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
get_const_value()
template<typename ValueType = default_precision, typename IndexType = int32> const value_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_value () const inline noexcept
Returns the value stored in the matrix.
Returns
the value of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
get_num_nonzeros()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::SparsityCsr< ValueType, IndexType >::get_num_nonzeros () const inline noexcept
Returns the number of elements explicitly stored in the matrix.
Returns
the number of elements explicitly stored in the matrix
References gko::Array< ValueType >::get_num_elems().
get_row_ptrs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_row_ptrs () inline noexcept
Returns the row pointers of the matrix.
Returns
the row pointers of the matrix.
References gko::Array< ValueType >::get_data().
get_value()
template<typename ValueType = default_precision, typename IndexType = int32> value_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_value () inline noexcept
Returns the value stored in the matrix.
Returns
the value of the matrix.
References gko::Array< ValueType >::get_data().
read()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::SparsityCsr< ValueType, IndexType >::read (const mat_data & data) override virtual
Reads a matrix from a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::ReadableFromMatrixData< ValueType, IndexType >.
to_adjacency_matrix()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<SparsityCsr> gko::matrix::SparsityCsr< ValueType, IndexType >::to_adjacency_matrix () const
Transforms the sparsity matrix to an adjacency matrix.
As the adjacency matrix has to be square, the input SparsityCsr matrix for this function to work has to be square.
Note
The adjacency matrix in this case is the sparsity pattern but with the diagonal ones removed. This is mainly used for the reordering/partitioning as taken in by graph libraries such as METIS.
transpose()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<LinOp> gko::matrix::SparsityCsr< ValueType, IndexType >::transpose () const override virtual
Returns a LinOp representing the transpose of the Transposable object.
Returns
a pointer to the new transposed object
Implements gko::Transposable.
write()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::SparsityCsr< ValueType, IndexType >::write (mat_data & data) const override virtual
Writes a matrix to a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::WritableToMatrixData< ValueType, IndexType >.
The documentation for this class was generated from the following files:
ginkgo/core/matrix/csr.hpp (2f671dafa)
ginkgo/core/matrix/sparsity_csr.hpp (2f671dafa)