Ginkgo: gko::matrix::Hybrid< ValueType, IndexType >::imbalance_bounded_limit Class Reference
gko::matrix::Hybrid< ValueType, IndexType >::imbalance_bounded_limit Class Reference
imbalance_bounded_limit is a strategy_type which decides the number of stored elements per row of the ell part.
#include <ginkgo/core/matrix/hybrid.hpp>
Public Member Functions
imbalance_bounded_limit (float percent=0.8, float ratio=0.0001)
Creates a imbalance_bounded_limit strategy.
size_type compute_ell_num_stored_elements_per_row (Array< size_type > *row_nnz) const override
Computes the number of stored elements per row of the ell part.
Public Member Functions inherited from gko::matrix::Hybrid< ValueType, IndexType >::strategy_type
strategy_type ()
Creates a strategy_type.
void compute_hybrid_config (const Array< size_type > &row_nnz, size_type *ell_num_stored_elements_per_row, size_type *coo_nnz)
Computes the config of the Hybrid matrix (ell_num_stored_elements_per_row and coo_nnz).
size_type get_ell_num_stored_elements_per_row () const noexcept
Returns the number of stored elements per row of the ell part.
size_type get_coo_nnz () const noexcept
Returns the number of nonzeros of the coo part.
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::Hybrid< ValueType, IndexType >::imbalance_bounded_limit
imbalance_bounded_limit is a strategy_type which decides the number of stored elements per row of the ell part.
It uses the imbalance_limit and adds the upper bound of the number of ell's cols by the number of rows.
Member Function Documentation
compute_ell_num_stored_elements_per_row()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Hybrid< ValueType, IndexType >::imbalance_bounded_limit::compute_ell_num_stored_elements_per_row (Array< size_type > * row_nnz) const inline override virtual
Computes the number of stored elements per row of the ell part.
Parameters
row_nnz the number of nonzeros of each row
Returns
the number of stored elements per row of the ell part
Implements gko::matrix::Hybrid< ValueType, IndexType >::strategy_type.
References gko::matrix::Hybrid< ValueType, IndexType >::imbalance_limit::compute_ell_num_stored_elements_per_row(), and gko::Array< ValueType >::get_num_elems().
Referenced by gko::matrix::Hybrid< ValueType, IndexType >::automatic::compute_ell_num_stored_elements_per_row().
The documentation for this class was generated from the following file:
ginkgo/core/matrix/hybrid.hpp (9a3dc7c52)