Ginkgo: gko::matrix::Csr< ValueType, IndexType >::automatical Class Reference
gko::matrix::Csr< ValueType, IndexType >::automatical Class Reference
Public Member Functions
automatical ()
Creates an automatical strategy.
automatical (std::shared_ptr< const CudaExecutor > exec)
Creates an automatical strategy with CUDA executor.
automatical (std::shared_ptr< const HipExecutor > exec)
Creates an automatical strategy with HIP executor.
automatical (int64_t nwarps, int warp_size=32, bool cuda_strategy=true)
Creates an automatical strategy with specified parameters.
void process (const Array< index_type > &mtx_row_ptrs, Array< index_type > *mtx_srow) override
Computes srow according to row pointers.
int64_t clac_size (const int64_t nnz) override
Computes the srow size according to the number of nonzeros.
index_type get_max_length_per_row () const noexcept
std::shared_ptr< strategy_type > copy () override
Copy a strategy.
Public Member Functions inherited from gko::matrix::Csr< ValueType, IndexType >::strategy_type
strategy_type (std::string name)
Creates a strategy_type.
std::string get_name ()
Returns the name of strategy.
Public Attributes
const index_type nvidia_row_len_limit = 1024
const index_type nvidia_nnz_limit = 1e6
const index_type amd_row_len_limit = 768
const index_type amd_nnz_limit = 1e8
Constructor & Destructor Documentation
automatical() [1/3]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::Csr< ValueType, IndexType >::automatical::automatical (std::shared_ptr< const CudaExecutor > exec) inline
Creates an automatical strategy with CUDA executor.
Parameters
exec the CUDA executor
automatical() [2/3]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::Csr< ValueType, IndexType >::automatical::automatical (std::shared_ptr< const HipExecutor > exec) inline
Creates an automatical strategy with HIP executor.
Parameters
exec the HIP executor
automatical() [3/3]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::Csr< ValueType, IndexType >::automatical::automatical (int64_t nwarps, int warp_size = 32, bool cuda_strategy = true) inline
Creates an automatical strategy with specified parameters.
Parameters
nwarps the number of warps in the executor
warp_size the warp size of the executor
cuda_strategy whether the cuda_strategy needs to be used.
Note
The warp_size must be the size of full warp. When using this constructor, set_strategy needs to be called with correct parameters which is replaced during the conversion.
Member Function Documentation
clac_size()
template<typename ValueType = default_precision, typename IndexType = int32> int64_t gko::matrix::Csr< ValueType, IndexType >::automatical::clac_size (const int64_t nnz) inline override virtual
Computes the srow size according to the number of nonzeros.
Parameters
nnz the number of nonzeros
Returns
the size of srow
Implements gko::matrix::Csr< ValueType, IndexType >::strategy_type.
copy()
template<typename ValueType = default_precision, typename IndexType = int32> std::shared_ptr<strategy_type> gko::matrix::Csr< ValueType, IndexType >::automatical::copy () inline override virtual
Copy a strategy.
This is a workaround until strategies are revamped, since strategies like automatical do not work when actually shared.
Implements gko::matrix::Csr< ValueType, IndexType >::strategy_type.
process()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Csr< ValueType, IndexType >::automatical::process (const Array< index_type > & mtx_row_ptrs, Array< index_type > * mtx_srow) inline override virtual
Computes srow according to row pointers.
Parameters
mtx_row_ptrs the row pointers of the matrix
mtx_srow the srow of the matrix
Implements gko::matrix::Csr< ValueType, IndexType >::strategy_type.
References gko::Array< ValueType >::get_const_data(), gko::Array< ValueType >::get_executor(), gko::matrix::Csr< ValueType, IndexType >::strategy_type::get_name(), gko::Array< ValueType >::get_num_elems(), gko::max(), gko::matrix::Csr< ValueType, IndexType >::classical::process(), and gko::matrix::Csr< ValueType, IndexType >::load_balance::process().
The documentation for this class was generated from the following file:
ginkgo/core/matrix/csr.hpp (9fdf77aa9)