function(split_list_average input_list num_parts)
    message("${input_list}")
    message("${${input_list}}")
    list(LENGTH ${input_list} total_length)
    message("${input_list} contains ${total_length}")
    message("generate total ${num_parts}")
    foreach(i RANGE 1 ${num_parts})
        message("generate ${i}")
        math(EXPR start "${total_length} * (${i} - 1) / ${num_parts}")
        math(EXPR end "${total_length} * ${i} / ${num_parts} - 1")
        message("${start} - ${end}")
        set(part "")
        foreach(j RANGE ${start} ${end})
            list(GET ${input_list} ${j} item)
            list(APPEND part ${item})
        endforeach()
        set(part_list_var ${input_list}_${i})
        set(${part_list_var} ${part} PARENT_SCOPE)
    endforeach()
endfunction()
