Ginkgo: gko::matrix::Coo< ValueType, IndexType > Class Template Reference
gko::matrix::Coo< ValueType, IndexType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | Linear Operators
COO stores a matrix in the coordinate matrix format.
#include <ginkgo/core/matrix/coo.hpp>
Public Types
using value_type = ValueType
using index_type = IndexType
using mat_data = matrix_data< ValueType, IndexType >
Public Types inherited from gko::EnablePolymorphicAssignment< Coo< ValueType, IndexType > >
using result_type = Coo< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Coo< ValueType, IndexType > >
using result_type = Coo< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Coo< next_precision< ValueType >, IndexType > >
using result_type = Coo< next_precision< ValueType >, IndexType >
Public Types inherited from gko::ConvertibleTo< Csr< ValueType, IndexType > >
using result_type = Csr< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Dense< ValueType > >
using result_type = Dense< ValueType >
Public Member Functions
void convert_to (Coo< next_precision< ValueType >, IndexType > *result) const override
void move_to (Coo< next_precision< ValueType >, IndexType > *result) override
void convert_to (Csr< ValueType, IndexType > *other) const override
void move_to (Csr< ValueType, IndexType > *other) override
void convert_to (Dense< ValueType > *other) const override
void move_to (Dense< ValueType > *other) override
void read (const mat_data &data) override
Reads a matrix from a matrix_data structure.
void write (mat_data &data) const override
Writes a matrix to a matrix_data structure.
value_type * get_values () noexcept
Returns the values of the matrix.
const value_type * get_const_values () const noexcept
Returns the values of the matrix.
index_type * get_col_idxs () noexcept
Returns the column indexes of the matrix.
const index_type * get_const_col_idxs () const noexcept
Returns the column indexes of the matrix.
index_type * get_row_idxs () noexcept
Returns the row indexes of the matrix.
const index_type * get_const_row_idxs () const noexcept
size_type get_num_stored_elements () const noexcept
Returns the number of elements explicitly stored in the matrix.
LinOp * apply2 (const LinOp *b, LinOp *x)
Applies Coo matrix axpy to a vector (or a sequence of vectors).
const LinOp * apply2 (const LinOp *b, LinOp *x) const
LinOp * apply2 (const LinOp *alpha, const LinOp *b, LinOp *x)
Performs the operation x = alpha * Coo * b + x.
const LinOp * apply2 (const LinOp *alpha, const LinOp *b, LinOp *x) const
Performs the operation x = alpha * Coo * b + x.
Public Member Functions inherited from gko::EnableLinOp< Coo< ValueType, IndexType > >
const Coo< ValueType, IndexType > * apply (const LinOp *b, LinOp *x) const
Coo< ValueType, IndexType > * apply (const LinOp *b, LinOp *x)
const Coo< ValueType, IndexType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Coo< ValueType, IndexType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< Coo< ValueType, IndexType >, LinOp >
std::unique_ptr< Coo< ValueType, IndexType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Coo< ValueType, IndexType > > create_default () const
std::unique_ptr< Coo< ValueType, IndexType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Coo< ValueType, IndexType > > clone () const
Coo< ValueType, IndexType > * copy_from (const PolymorphicObject *other)
Coo< ValueType, IndexType > * copy_from (std::unique_ptr< PolymorphicObject > other)
Coo< ValueType, IndexType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (const LinOp *b, LinOp *x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (const LinOp *b, LinOp *x) const
Applies a linear operator to a vector (or a sequence of vectors).
LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Performs the operation x = alpha * op(b) + beta * x.
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
virtual bool apply_uses_initial_guess () const
Returns true if the linear operator uses the data given in x as an initial guess.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
LinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
Adds a new logger to the list of subscribed loggers.
void remove_logger (const Logger *logger) override
Removes a logger from the list of subscribed loggers.
Public Member Functions inherited from gko::EnablePolymorphicAssignment< Coo< ValueType, IndexType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Coo< next_precision< ValueType >, IndexType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Csr< ValueType, IndexType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Dense< ValueType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Friends
class EnableCreateMethod< Coo >
class EnablePolymorphicObject< Coo, LinOp >
class Csr< ValueType, IndexType >
class Dense< ValueType >
class CooBuilder< ValueType, IndexType >
class Coo< next_precision< ValueType >, IndexType >
Additional Inherited Members
Static Public Member Functions inherited from gko::EnableCreateMethod< Coo< ValueType, IndexType > >
static std::unique_ptr< Coo< ValueType, IndexType > > create (Args &&... args)
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::Coo< ValueType, IndexType >
COO stores a matrix in the coordinate matrix format.
The nonzero elements are stored in an array row-wise (but not neccessarily sorted by column index within a row). Two extra arrays contain the row and column indexes of each nonzero element of the matrix.
Template Parameters
ValueType precision of matrix elements
IndexType precision of matrix indexes
Member Function Documentation
apply2() [1/4]
template<typename ValueType = default_precision, typename IndexType = int32> LinOp* gko::matrix::Coo< ValueType, IndexType >::apply2 (const LinOp * alpha, const LinOp * b, LinOp * x) inline
Performs the operation x = alpha * Coo * b + x.
Parameters
alpha scaling of the result of Coo * b
b vector(s) on which the operator is applied
x output vector(s)
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
apply2() [2/4]
template<typename ValueType = default_precision, typename IndexType = int32> const LinOp* gko::matrix::Coo< ValueType, IndexType >::apply2 (const LinOp * alpha, const LinOp * b, LinOp * x) const inline
Performs the operation x = alpha * Coo * b + x.
Parameters
alpha scaling of the result of Coo * b
b vector(s) on which the operator is applied
x output vector(s)
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
apply2() [3/4]
template<typename ValueType = default_precision, typename IndexType = int32> LinOp* gko::matrix::Coo< ValueType, IndexType >::apply2 (const LinOp * b, LinOp * x) inline
Applies Coo matrix axpy to a vector (or a sequence of vectors).
Performs the operation x = Coo * b + x
Parameters
b the input vector(s) on which the operator is applied
x the output vector(s) where the result is stored
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
apply2() [4/4]
template<typename ValueType = default_precision, typename IndexType = int32> const LinOp* gko::matrix::Coo< ValueType, IndexType >::apply2 (const LinOp * b, LinOp * x) const inline
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
get_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::Coo< ValueType, IndexType >::get_col_idxs () inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
References gko::Array< ValueType >::get_data().
get_const_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::Coo< ValueType, IndexType >::get_const_col_idxs () const inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
get_const_row_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::Coo< ValueType, IndexType >::get_const_row_idxs () const inline noexcept
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
get_const_values()
template<typename ValueType = default_precision, typename IndexType = int32> const value_type* gko::matrix::Coo< ValueType, IndexType >::get_const_values () const inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
get_num_stored_elements()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Coo< ValueType, IndexType >::get_num_stored_elements () const inline noexcept
Returns the number of elements explicitly stored in the matrix.
Returns
the number of elements explicitly stored in the matrix
References gko::Array< ValueType >::get_num_elems().
get_row_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::Coo< ValueType, IndexType >::get_row_idxs () inline noexcept
Returns the row indexes of the matrix.
Returns
the row indexes of the matrix.
References gko::Array< ValueType >::get_data().
get_values()
template<typename ValueType = default_precision, typename IndexType = int32> value_type* gko::matrix::Coo< ValueType, IndexType >::get_values () inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
References gko::Array< ValueType >::get_data().
read()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Coo< ValueType, IndexType >::read (const mat_data & data) override virtual
Reads a matrix from a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::ReadableFromMatrixData< ValueType, IndexType >.
write()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Coo< ValueType, IndexType >::write (mat_data & data) const override virtual
Writes a matrix to a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::WritableToMatrixData< ValueType, IndexType >.
The documentation for this class was generated from the following file:
ginkgo/core/matrix/coo.hpp (8a86dad58)