Ginkgo: gko::matrix::Ell< ValueType, IndexType > Class Template Reference
gko::matrix::Ell< ValueType, IndexType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | Linear Operators
ELL is a matrix format where stride with explicit zeros is used such that all rows have the same number of stored elements.
#include <ginkgo/core/matrix/ell.hpp>
Public Types
using value_type = ValueType
using index_type = IndexType
using mat_data = matrix_data< ValueType, IndexType >
Public Types inherited from gko::EnablePolymorphicAssignment< Ell< ValueType, IndexType > >
using result_type = Ell< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Ell< ValueType, IndexType > >
using result_type = Ell< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Dense< ValueType > >
using result_type = Dense< ValueType >
Public Types inherited from gko::ConvertibleTo< Csr< ValueType, IndexType > >
using result_type = Csr< ValueType, IndexType >
Public Member Functions
void convert_to (Dense< ValueType > *other) const override
void move_to (Dense< ValueType > *other) override
void convert_to (Csr< ValueType, IndexType > *other) const override
void move_to (Csr< ValueType, IndexType > *other) override
void read (const mat_data &data) override
Reads a matrix from a matrix_data structure.
void write (mat_data &data) const override
Writes a matrix to a matrix_data structure.
value_type * get_values () noexcept
Returns the values of the matrix.
const value_type * get_const_values () const noexcept
Returns the values of the matrix.
index_type * get_col_idxs () noexcept
Returns the column indexes of the matrix.
const index_type * get_const_col_idxs () const noexcept
Returns the column indexes of the matrix.
size_type get_num_stored_elements_per_row () const noexcept
Returns the number of stored elements per row.
size_type get_stride () const noexcept
Returns the stride of the matrix.
size_type get_num_stored_elements () const noexcept
Returns the number of elements explicitly stored in the matrix.
value_type & val_at (size_type row, size_type idx) noexcept
Returns the idx-th non-zero element of the row-th row .
value_type val_at (size_type row, size_type idx) const noexcept
Returns the idx-th non-zero element of the row-th row .
index_type & col_at (size_type row, size_type idx) noexcept
Returns the idx-th column index of the row-th row .
index_type col_at (size_type row, size_type idx) const noexcept
Returns the idx-th column index of the row-th row .
Public Member Functions inherited from gko::EnableLinOp< Ell< ValueType, IndexType > >
const Ell< ValueType, IndexType > * apply (const LinOp *b, LinOp *x) const
Ell< ValueType, IndexType > * apply (const LinOp *b, LinOp *x)
const Ell< ValueType, IndexType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Ell< ValueType, IndexType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< Ell< ValueType, IndexType >, LinOp >
std::unique_ptr< Ell< ValueType, IndexType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Ell< ValueType, IndexType > > create_default () const
std::unique_ptr< Ell< ValueType, IndexType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Ell< ValueType, IndexType > > clone () const
Ell< ValueType, IndexType > * copy_from (const PolymorphicObject *other)
Ell< ValueType, IndexType > * copy_from (std::unique_ptr< PolymorphicObject > other)
Ell< ValueType, IndexType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (const LinOp *b, LinOp *x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (const LinOp *b, LinOp *x) const
Applies a linear operator to a vector (or a sequence of vectors).
LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Performs the operation x = alpha * op(b) + beta * x.
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
LinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
Adds a new logger to the list of subscribed loggers.
void remove_logger (const Logger *logger) override
Removes a logger from the list of subscribed loggers.
Public Member Functions inherited from gko::EnablePolymorphicAssignment< Ell< ValueType, IndexType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Dense< ValueType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Csr< ValueType, IndexType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Friends
class EnableCreateMethod< Ell >
class EnablePolymorphicObject< Ell, LinOp >
class Dense< ValueType >
class Csr< ValueType, IndexType >
Additional Inherited Members
Static Public Member Functions inherited from gko::EnableCreateMethod< Ell< ValueType, IndexType > >
static std::unique_ptr< Ell< ValueType, IndexType > > create (Args &&... args)
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::Ell< ValueType, IndexType >
ELL is a matrix format where stride with explicit zeros is used such that all rows have the same number of stored elements.
The number of elements stored in each row is the largest number of nonzero elements in any of the rows (obtainable through get_num_stored_elements_per_row() method). This removes the need of a row pointer like in the CSR format, and allows for SIMD processing of the distinct rows. For efficient processing, the nonzero elements and the corresponding column indices are stored in column-major fashion. The columns are padded to the length by user-defined stride parameter whose default value is the number of rows of the matrix.
Template Parameters
ValueType precision of matrix elements
IndexType precision of matrix indexes
Member Function Documentation
col_at() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> index_type gko::matrix::Ell< ValueType, IndexType >::col_at (size_type row, size_type idx) const inline noexcept
Returns the idx-th column index of the row-th row .
Parameters
row the row of the requested element
idx the idx-th stored element of the row
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::matrix::Ell< ValueType, IndexType >::get_const_col_idxs().
col_at() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> index_type& gko::matrix::Ell< ValueType, IndexType >::col_at (size_type row, size_type idx) inline noexcept
Returns the idx-th column index of the row-th row .
Parameters
row the row of the requested element
idx the idx-th stored element of the row
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::matrix::Ell< ValueType, IndexType >::get_col_idxs().
get_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::Ell< ValueType, IndexType >::get_col_idxs () inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
References gko::Array< ValueType >::get_data().
Referenced by gko::matrix::Ell< ValueType, IndexType >::col_at().
get_const_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::Ell< ValueType, IndexType >::get_const_col_idxs () const inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
Referenced by gko::matrix::Ell< ValueType, IndexType >::col_at().
get_const_values()
template<typename ValueType = default_precision, typename IndexType = int32> const value_type* gko::matrix::Ell< ValueType, IndexType >::get_const_values () const inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
get_num_stored_elements()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Ell< ValueType, IndexType >::get_num_stored_elements () const inline noexcept
Returns the number of elements explicitly stored in the matrix.
Returns
the number of elements explicitly stored in the matrix
References gko::Array< ValueType >::get_num_elems().
get_num_stored_elements_per_row()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Ell< ValueType, IndexType >::get_num_stored_elements_per_row () const inline noexcept
Returns the number of stored elements per row.
Returns
the number of stored elements per row.
get_stride()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Ell< ValueType, IndexType >::get_stride () const inline noexcept
Returns the stride of the matrix.
Returns
the stride of the matrix.
get_values()
template<typename ValueType = default_precision, typename IndexType = int32> value_type* gko::matrix::Ell< ValueType, IndexType >::get_values () inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
References gko::Array< ValueType >::get_data().
read()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Ell< ValueType, IndexType >::read (const mat_data & data) override virtual
Reads a matrix from a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::ReadableFromMatrixData< ValueType, IndexType >.
val_at() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> value_type gko::matrix::Ell< ValueType, IndexType >::val_at (size_type row, size_type idx) const inline noexcept
Returns the idx-th non-zero element of the row-th row .
Parameters
row the row of the requested element
idx the idx-th stored element of the row
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::Array< ValueType >::get_const_data().
val_at() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> value_type& gko::matrix::Ell< ValueType, IndexType >::val_at (size_type row, size_type idx) inline noexcept
Returns the idx-th non-zero element of the row-th row .
Parameters
row the row of the requested element
idx the idx-th stored element of the row
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::Array< ValueType >::get_data().
write()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Ell< ValueType, IndexType >::write (mat_data & data) const override virtual
Writes a matrix to a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::WritableToMatrixData< ValueType, IndexType >.
The documentation for this class was generated from the following files:
ginkgo/core/matrix/csr.hpp (b8bd4773)
ginkgo/core/matrix/ell.hpp (8045ac75)