Ginkgo: gko::matrix::Csr< ValueType, IndexType >::load_balance Class Reference
gko::matrix::Csr< ValueType, IndexType >::load_balance Class Reference
load_balance is a strategy_type which uses the load balance algorithm.
#include <ginkgo/core/matrix/csr.hpp>
Public Member Functions
load_balance ()
Creates a load_balance strategy.
load_balance (std::shared_ptr< const CudaExecutor > exec)
Creates a load_balance strategy with CUDA executor.
load_balance (std::shared_ptr< const HipExecutor > exec)
Creates a load_balance strategy with HIP executor.
load_balance (int64_t nwarps, int warp_size=32, bool cuda_strategy=true)
Creates a load_balance strategy with specified parameters.
void process (const Array< index_type > &mtx_row_ptrs, Array< index_type > *mtx_srow) override
Computes srow according to row pointers.
int64_t clac_size (const int64_t nnz) override
Computes the srow size according to the number of nonzeros.
Public Member Functions inherited from gko::matrix::Csr< ValueType, IndexType >::strategy_type
strategy_type (std::string name)
Creates a strategy_type.
std::string get_name ()
Returns the name of strategy.
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::Csr< ValueType, IndexType >::load_balance
load_balance is a strategy_type which uses the load balance algorithm.
Constructor & Destructor Documentation
load_balance() [1/3]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::Csr< ValueType, IndexType >::load_balance::load_balance (std::shared_ptr< const CudaExecutor > exec) inline
Creates a load_balance strategy with CUDA executor.
Parameters
exec the CUDA executor
load_balance() [2/3]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::Csr< ValueType, IndexType >::load_balance::load_balance (std::shared_ptr< const HipExecutor > exec) inline
Creates a load_balance strategy with HIP executor.
Parameters
exec the HIP executor
load_balance() [3/3]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::Csr< ValueType, IndexType >::load_balance::load_balance (int64_t nwarps, int warp_size = 32, bool cuda_strategy = true) inline
Creates a load_balance strategy with specified parameters.
Parameters
nwarps the number of warps in the executor
warp_size the warp size of the executor
cuda_strategy whether the cuda_strategy needs to be used.
Note
The warp_size must be the size of full warp. When using this constructor, set_strategy needs to be called with correct parameters which is replaced during the conversion.
Member Function Documentation
clac_size()
template<typename ValueType = default_precision, typename IndexType = int32> int64_t gko::matrix::Csr< ValueType, IndexType >::load_balance::clac_size (const int64_t nnz) inline override virtual
Computes the srow size according to the number of nonzeros.
Parameters
nnz the number of nonzeros
Returns
the size of srow
Implements gko::matrix::Csr< ValueType, IndexType >::strategy_type.
References gko::ceildiv(), and gko::min().
process()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Csr< ValueType, IndexType >::load_balance::process (const Array< index_type > & mtx_row_ptrs, Array< index_type > * mtx_srow) inline override virtual
Computes srow according to row pointers.
Parameters
mtx_row_ptrs the row pointers of the matrix
mtx_srow the srow of the matrix
Implements gko::matrix::Csr< ValueType, IndexType >::strategy_type.
References gko::ceildiv(), gko::Array< ValueType >::get_const_data(), gko::Array< ValueType >::get_data(), gko::Array< ValueType >::get_executor(), and gko::Array< ValueType >::get_num_elems().
Referenced by gko::matrix::Csr< ValueType, IndexType >::automatical::process().
The documentation for this class was generated from the following file:
ginkgo/core/matrix/csr.hpp (8e675e0b5)