Ginkgo: gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType > Class Template Reference
gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType > Class Template Reference
Linear Operators » Preconditioners | Linear Operators
The Incomplete LU (ILU) preconditioner solves the equation for a given lower triangular matrix L, an upper triangular matrix U and the right hand side b (can contain multiple right hand sides).
#include <ginkgo/core/preconditioner/ilu.hpp>
Classes
class Factory
struct parameters_type
Public Types
using value_type = typename LSolverType::value_type
using l_solver_type = LSolverType
using u_solver_type = USolverType
using index_type = IndexType
using transposed_type = Ilu< typename USolverType::transposed_type, typename LSolverType::transposed_type, ReverseApply, IndexType >
Public Types inherited from gko::EnablePolymorphicAssignment< Ilu< LSolverType, USolverType, ReverseApply, IndexType > >
using result_type = Ilu< LSolverType, USolverType, ReverseApply, IndexType >
Public Types inherited from gko::ConvertibleTo< Ilu< LSolverType, USolverType, ReverseApply, IndexType > >
using result_type = Ilu< LSolverType, USolverType, ReverseApply, IndexType >
Public Member Functions
const parameters_type & get_parameters () const
std::shared_ptr< const l_solver_type > get_l_solver () const
Returns the solver which is used for the provided L matrix.
std::shared_ptr< const u_solver_type > get_u_solver () const
Returns the solver which is used for the provided U matrix.
std::unique_ptr< LinOp > transpose () const override
Returns a LinOp representing the transpose of the Transposable object.
std::unique_ptr< LinOp > conj_transpose () const override
Returns a LinOp representing the conjugate transpose of the Transposable object.
Public Member Functions inherited from gko::EnableLinOp< Ilu< LSolverType, USolverType, ReverseApply, IndexType > >
const Ilu< LSolverType, USolverType, ReverseApply, IndexType > * apply (const LinOp *b, LinOp *x) const
Ilu< LSolverType, USolverType, ReverseApply, IndexType > * apply (const LinOp *b, LinOp *x)
const Ilu< LSolverType, USolverType, ReverseApply, IndexType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Ilu< LSolverType, USolverType, ReverseApply, IndexType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< Ilu< LSolverType, USolverType, ReverseApply, IndexType >, LinOp >
std::unique_ptr< Ilu< LSolverType, USolverType, ReverseApply, IndexType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Ilu< LSolverType, USolverType, ReverseApply, IndexType > > create_default () const
std::unique_ptr< Ilu< LSolverType, USolverType, ReverseApply, IndexType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Ilu< LSolverType, USolverType, ReverseApply, IndexType > > clone () const
Ilu< LSolverType, USolverType, ReverseApply, IndexType > * copy_from (const PolymorphicObject *other)
Ilu< LSolverType, USolverType, ReverseApply, IndexType > * copy_from (std::unique_ptr< PolymorphicObject > other)
Ilu< LSolverType, USolverType, ReverseApply, IndexType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (const LinOp *b, LinOp *x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (const LinOp *b, LinOp *x) const
Applies a linear operator to a vector (or a sequence of vectors).
LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Performs the operation x = alpha * op(b) + beta * x.
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
virtual bool apply_uses_initial_guess () const
Returns true if the linear operator uses the data given in x as an initial guess.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
LinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
Adds a new logger to the list of subscribed loggers.
void remove_logger (const Logger *logger) override
Removes a logger from the list of subscribed loggers.
Public Member Functions inherited from gko::EnablePolymorphicAssignment< Ilu< LSolverType, USolverType, ReverseApply, IndexType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Static Public Member Functions
static auto build () -> decltype(Factory ::create())
Static Public Attributes
static constexpr bool performs_reverse_apply = ReverseApply
Friends
class EnableLinOp< Ilu >
class EnablePolymorphicObject< Ilu, LinOp >
Detailed Description
template<typename LSolverType = solver::LowerTrs<>, typename USolverType = solver::UpperTrs<>, bool ReverseApply = false, typename IndexType = int32>
class gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >
The Incomplete LU (ILU) preconditioner solves the equation for a given lower triangular matrix L, an upper triangular matrix U and the right hand side b (can contain multiple right hand sides).
It allows to set both the solver for L and the solver for U independently, while providing the defaults solver::LowerTrs and solver::UpperTrs, which are direct triangular solvers. For these solvers, a factory can be provided (with with_l_solver_factory and with_u_solver_factory) to have more control over their behavior. In particular, it is possible to use an iterative method for solving the triangular systems. The default parameters for an iterative triangluar solver are:
reduction factor = 1e-4
max iteration = <number of="" rows="" of="" the="" matrix="" given="" to="" the="" solver>=""> Solvers without such criteria can also be used, in which case none are set.
An object of this class can be created with a matrix or a gko::Composition containing two matrices. If created with a matrix, it is factorized before creating the solver. If a gko::Composition (containing two matrices) is used, the first operand will be taken as the L matrix, the second will be considered the U matrix. ParIlu can be directly used, since it orders the factors in the correct way.
Note
When providing a gko::Composition, the first matrix must be the lower matrix (), and the second matrix must be the upper matrix (). If they are swapped, solving might crash or return the wrong result.
Do not use symmetric solvers (like CG) for L or U solvers since both matrices (L and U) are, by design, not symmetric.
This class is not thread safe (even a const object is not) because it uses an internal cache to accelerate multiple (sequential) applies. Using it in parallel can lead to segmentation faults, wrong results and other unwanted behavior.
Template Parameters
LSolverType type of the solver used for the L matrix. Defaults to solver::LowerTrs
USolverType type of the solver used for the U matrix Defaults to solver::UpperTrs
ReverseApply default behavior (ReverseApply = false) is first to solve with L (Ly = b) and then with U (Ux = y). When set to true, it will solve first with U, and then with L.
IndexTypeParIlu Type of the indices when ParIlu is used to generate both L and U factors. Irrelevant otherwise.
Member Function Documentation
conj_transpose()
template<typename LSolverType = solver::LowerTrs<>, typename USolverType = solver::UpperTrs<>, bool ReverseApply = false, typename IndexType = int32> std::unique_ptr<LinOp> gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::conj_transpose () const inline override virtual
Returns a LinOp representing the conjugate transpose of the Transposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::Transposable.
References gko::PolymorphicObject::get_executor(), gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::get_l_solver(), gko::LinOp::get_size(), gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::get_u_solver(), gko::share(), and gko::transpose().
get_l_solver()
template<typename LSolverType = solver::LowerTrs<>, typename USolverType = solver::UpperTrs<>, bool ReverseApply = false, typename IndexType = int32> std::shared_ptr<const l_solver_type> gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::get_l_solver () const inline
Returns the solver which is used for the provided L matrix.
Returns
the solver which is used for the provided L matrix
Referenced by gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::conj_transpose(), and gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::transpose().
get_u_solver()
template<typename LSolverType = solver::LowerTrs<>, typename USolverType = solver::UpperTrs<>, bool ReverseApply = false, typename IndexType = int32> std::shared_ptr<const u_solver_type> gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::get_u_solver () const inline
Returns the solver which is used for the provided U matrix.
Returns
the solver which is used for the provided U matrix
Referenced by gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::conj_transpose(), and gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::transpose().
transpose()
template<typename LSolverType = solver::LowerTrs<>, typename USolverType = solver::UpperTrs<>, bool ReverseApply = false, typename IndexType = int32> std::unique_ptr<LinOp> gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::transpose () const inline override virtual
Returns a LinOp representing the transpose of the Transposable object.
Returns
a pointer to the new transposed object
Implements gko::Transposable.
References gko::PolymorphicObject::get_executor(), gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::get_l_solver(), gko::LinOp::get_size(), gko::preconditioner::Ilu< LSolverType, USolverType, ReverseApply, IndexType >::get_u_solver(), gko::share(), and gko::transpose().
The documentation for this class was generated from the following file:
ginkgo/core/preconditioner/ilu.hpp (b0974c2ae)