Ginkgo: gko::Array< ValueType > Class Template Reference
gko::Array< ValueType > Class Template Reference
An Array is a container which encapsulates fixed-sized arrays, stored on the Executor tied to the Array.
#include <ginkgo/core/base/array.hpp>
Public Types
using value_type = ValueType
The type of elements stored in the array.
using default_deleter = executor_deleter< value_type[]>
The default deleter type used by Array.
using view_deleter = null_deleter< value_type[]>
The deleter type used for views.
Public Member Functions
Array () noexcept
Creates an empty Array not tied to any executor.
Array (std::shared_ptr< const Executor > exec) noexcept
Creates an empty Array tied to the specified Executor.
Array (std::shared_ptr< const Executor > exec, size_type num_elems)
Creates an Array on the specified Executor.
template<typename DeleterType >
Array (std::shared_ptr< const Executor > exec, size_type num_elems, value_type *data, DeleterType deleter)
Creates an Array from existing memory.
Array (std::shared_ptr< const Executor > exec, size_type num_elems, value_type *data)
Creates an Array from existing memory.
template<typename RandomAccessIterator >
Array (std::shared_ptr< const Executor > exec, RandomAccessIterator begin, RandomAccessIterator end)
Creates an array on the specified Executor and initializes it with values.
template<typename T >
Array (std::shared_ptr< const Executor > exec, std::initializer_list< T > init_list)
Creates an array on the specified Executor and initializes it with values.
Array (std::shared_ptr< const Executor > exec, const Array &other)
Creates a copy of another array on a different executor.
Array (const Array &other)
Creates a copy of another array.
Array (std::shared_ptr< const Executor > exec, Array &&other)
Moves another array to a different executor.
Array (Array &&other)
Moves another array.
Array & operator= (const Array &other)
Copies data from another array or view.
Array & operator= (Array &&other)
Moves data from another array or view.
template<typename OtherValueType >
xstd::enable_if_t<!std::is_same< ValueType, OtherValueType >::value, Array > & operator= (const Array< OtherValueType > &other)
Copies and converts data from another array with another data type.
void clear () noexcept
Deallocates all data used by the Array.
void resize_and_reset (size_type num_elems)
Resizes the array so it is able to hold the specified number of elements.
size_type get_num_elems () const noexcept
Returns the number of elements in the Array.
value_type * get_data () noexcept
Returns a pointer to the block of memory used to store the elements of the Array.
const value_type * get_const_data () const noexcept
Returns a constant pointer to the block of memory used to store the elements of the Array.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor associated with the array.
void set_executor (std::shared_ptr< const Executor > exec)
Changes the Executor of the Array, moving the allocated data to the new Executor.
bool is_owning ()
Tells whether this Array owns its data or not.
Static Public Member Functions
static Array view (std::shared_ptr< const Executor > exec, size_type num_elems, value_type *data)
Creates an Array from existing memory.
Friends
template<typename OtherValueType >
class Array
Detailed Description
template<typename ValueType>
class gko::Array< ValueType >
An Array is a container which encapsulates fixed-sized arrays, stored on the Executor tied to the Array.
The array stores and transfers its data as raw memory, which means that the constructors of its elements are not called when constructing, copying or moving the Array. Thus, the Array class is most suitable for storing POD types.
Template Parameters
ValueType the type of elements stored in the array
Constructor & Destructor Documentation
Array() [1/11]
template<typename ValueType> gko::Array< ValueType >::Array () inline noexcept
Creates an empty Array not tied to any executor.
An array without an assigned executor can only be empty. Attempts to change its size (e.g. via the resize_and_reset method) will result in an exception. If such an array is used as the right hand side of an assignment or move assignment expression, the data of the target array will be cleared, but its executor will not be modified.
The executor can later be set by using the set_executor method. If an Array with no assigned executor is assigned or moved to, it will inherit the executor of the source Array.
Array() [2/11]
template<typename ValueType> gko::Array< ValueType >::Array (std::shared_ptr< const Executor > exec) inline noexcept
Creates an empty Array tied to the specified Executor.
Parameters
exec the Executor where the array data is allocated
Array() [3/11]
template<typename ValueType> gko::Array< ValueType >::Array (std::shared_ptr< const Executor > exec, size_type num_elems) inline
Creates an Array on the specified Executor.
Parameters
exec the Executor where the array data will be allocated
num_elems the amount of memory (expressed as the number of value_type elements) allocated on the Executor
Array() [4/11]
template<typename ValueType> template<typename DeleterType > gko::Array< ValueType >::Array (std::shared_ptr< const Executor > exec, size_type num_elems, value_type * data, DeleterType deleter) inline
Creates an Array from existing memory.
The memory will be managed by the array, and deallocated using the specified deleter (e.g. use std::default_delete for data allocated with new).
Template Parameters
DeleterType type of the deleter
Parameters
exec executor where data is located
num_elems number of elements in data
data chunk of memory used to create the array
deleter the deleter used to free the memory
See also
Array::view() to create an array that does not deallocate memory
Array(std::shared_ptr<cont Executor>, size_type, value_type*) to deallocate the memory using Executor::free() method
Array() [5/11]
template<typename ValueType> gko::Array< ValueType >::Array (std::shared_ptr< const Executor > exec, size_type num_elems, value_type * data) inline
Creates an Array from existing memory.
The memory will be managed by the array, and deallocated using the Executor::free method.
Parameters
exec executor where data is located
num_elems number of elements in data
data chunk of memory used to create the array
Array() [6/11]
template<typename ValueType> template<typename RandomAccessIterator > gko::Array< ValueType >::Array (std::shared_ptr< const Executor > exec, RandomAccessIterator begin, RandomAccessIterator end) inline
Creates an array on the specified Executor and initializes it with values.
Template Parameters
RandomAccessIterator type of the iterators
Parameters
exec the Executor where the array data will be allocated
begin start of range of values
end end of range of values
Array() [7/11]
template<typename ValueType> template<typename T > gko::Array< ValueType >::Array (std::shared_ptr< const Executor > exec, std::initializer_list< T > init_list) inline
Creates an array on the specified Executor and initializes it with values.
Template Parameters
T type of values used to initialize the array (T has to be implicitly convertible to value_type)
Parameters
exec the Executor where the array data will be allocated
init_list list of values used to initialize the Array
Array() [8/11]
template<typename ValueType> gko::Array< ValueType >::Array (std::shared_ptr< const Executor > exec, const Array< ValueType > & other) inline
Creates a copy of another array on a different executor.
This does not invoke the constructors of the elements, instead they are copied as POD types.
Parameters
exec the executor where the new array will be created
other the Array to copy from
Array() [9/11]
template<typename ValueType> gko::Array< ValueType >::Array (const Array< ValueType > & other) inline
Creates a copy of another array.
This does not invoke the constructors of the elements, instead they are copied as POD types.
Parameters
other the Array to copy from
Array() [10/11]
template<typename ValueType> gko::Array< ValueType >::Array (std::shared_ptr< const Executor > exec, Array< ValueType > && other) inline
Moves another array to a different executor.
This does not invoke the constructors of the elements, instead they are copied as POD types.
Parameters
exec the executor where the new array will be moved
other the Array to move
Array() [11/11]
template<typename ValueType> gko::Array< ValueType >::Array (Array< ValueType > && other) inline
Moves another array.
This does not invoke the constructors of the elements, instead they are copied as POD types.
Parameters
other the Array to move
Member Function Documentation
clear()
template<typename ValueType> void gko::Array< ValueType >::clear () inline noexcept
Deallocates all data used by the Array.
The array is left in a valid, but empty state, so the same array can be used to allocate new memory. Calls to Array::get_data() will return a nullptr.
Referenced by gko::Array< index_type >::operator=(), and gko::Array< index_type >::resize_and_reset().
get_const_data()
template<typename ValueType> const value_type* gko::Array< ValueType >::get_const_data () const inline noexcept
Returns a constant pointer to the block of memory used to store the elements of the Array.
Returns
a constant pointer to the block of memory used to store the elements of the Array
Referenced by gko::matrix::Dense< ValueType >::at(), gko::preconditioner::Jacobi< ValueType, IndexType >::get_blocks(), gko::preconditioner::Jacobi< ValueType, IndexType >::get_conditioning(), gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_col_idxs(), gko::matrix::Sellp< ValueType, IndexType >::get_const_col_idxs(), gko::matrix::Ell< ValueType, IndexType >::get_const_col_idxs(), gko::matrix::Coo< ValueType, IndexType >::get_const_col_idxs(), gko::matrix::Csr< ValueType, IndexType >::get_const_col_idxs(), gko::matrix::Permutation< IndexType >::get_const_permutation(), gko::matrix::Coo< ValueType, IndexType >::get_const_row_idxs(), gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_row_ptrs(), gko::matrix::Csr< ValueType, IndexType >::get_const_row_ptrs(), gko::matrix::Sellp< ValueType, IndexType >::get_const_slice_lengths(), gko::matrix::Sellp< ValueType, IndexType >::get_const_slice_sets(), gko::matrix::Csr< ValueType, IndexType >::get_const_srow(), gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_value(), gko::matrix::Sellp< ValueType, IndexType >::get_const_values(), gko::matrix::Ell< ValueType, IndexType >::get_const_values(), gko::matrix::Coo< ValueType, IndexType >::get_const_values(), gko::matrix::Dense< ValueType >::get_const_values(), gko::matrix::Csr< ValueType, IndexType >::get_const_values(), gko::Array< index_type >::operator=(), gko::matrix::Csr< ValueType, IndexType >::classical::process(), gko::matrix::Csr< ValueType, IndexType >::load_balance::process(), gko::matrix::Csr< ValueType, IndexType >::automatical::process(), gko::matrix::Ell< ValueType, IndexType >::val_at(), and gko::matrix::Sellp< ValueType, IndexType >::val_at().
get_data()
template<typename ValueType> value_type* gko::Array< ValueType >::get_data () inline noexcept
Returns a pointer to the block of memory used to store the elements of the Array.
Returns
a pointer to the block of memory used to store the elements of the Array
Referenced by gko::matrix::Dense< ValueType >::at(), gko::matrix::Hybrid< ValueType, IndexType >::imbalance_limit::compute_ell_num_stored_elements_per_row(), gko::matrix::SparsityCsr< ValueType, IndexType >::get_col_idxs(), gko::matrix::Sellp< ValueType, IndexType >::get_col_idxs(), gko::matrix::Ell< ValueType, IndexType >::get_col_idxs(), gko::matrix::Coo< ValueType, IndexType >::get_col_idxs(), gko::matrix::Csr< ValueType, IndexType >::get_col_idxs(), gko::matrix::Permutation< IndexType >::get_permutation(), gko::matrix::Coo< ValueType, IndexType >::get_row_idxs(), gko::matrix::SparsityCsr< ValueType, IndexType >::get_row_ptrs(), gko::matrix::Csr< ValueType, IndexType >::get_row_ptrs(), gko::matrix::Sellp< ValueType, IndexType >::get_slice_lengths(), gko::matrix::Sellp< ValueType, IndexType >::get_slice_sets(), gko::matrix::Csr< ValueType, IndexType >::get_srow(), gko::matrix::SparsityCsr< ValueType, IndexType >::get_value(), gko::matrix::Sellp< ValueType, IndexType >::get_values(), gko::matrix::Ell< ValueType, IndexType >::get_values(), gko::matrix::Coo< ValueType, IndexType >::get_values(), gko::matrix::Dense< ValueType >::get_values(), gko::matrix::Csr< ValueType, IndexType >::get_values(), gko::Array< index_type >::operator=(), gko::matrix::Csr< ValueType, IndexType >::load_balance::process(), gko::matrix::Ell< ValueType, IndexType >::val_at(), and gko::matrix::Sellp< ValueType, IndexType >::val_at().
get_executor()
template<typename ValueType> std::shared_ptr<const Executor> gko::Array< ValueType >::get_executor () const inline noexcept
Returns the Executor associated with the array.
Returns
the Executor associated with the array
Referenced by gko::matrix::Hybrid< ValueType, IndexType >::strategy_type::compute_hybrid_config(), gko::Array< index_type >::operator=(), gko::matrix::Csr< ValueType, IndexType >::classical::process(), gko::matrix::Csr< ValueType, IndexType >::load_balance::process(), and gko::matrix::Csr< ValueType, IndexType >::automatical::process().
get_num_elems()
template<typename ValueType> size_type gko::Array< ValueType >::get_num_elems () const inline noexcept
Returns the number of elements in the Array.
Returns
the number of elements in the Array
Referenced by gko::matrix::Hybrid< ValueType, IndexType >::imbalance_limit::compute_ell_num_stored_elements_per_row(), gko::matrix::Hybrid< ValueType, IndexType >::imbalance_bounded_limit::compute_ell_num_stored_elements_per_row(), gko::matrix::Hybrid< ValueType, IndexType >::strategy_type::compute_hybrid_config(), gko::matrix::SparsityCsr< ValueType, IndexType >::get_num_nonzeros(), gko::matrix::Csr< ValueType, IndexType >::get_num_srow_elements(), gko::matrix::Ell< ValueType, IndexType >::get_num_stored_elements(), gko::matrix::Coo< ValueType, IndexType >::get_num_stored_elements(), gko::matrix::Sellp< ValueType, IndexType >::get_num_stored_elements(), gko::matrix::Dense< ValueType >::get_num_stored_elements(), gko::preconditioner::Jacobi< ValueType, IndexType >::get_num_stored_elements(), gko::matrix::Csr< ValueType, IndexType >::get_num_stored_elements(), gko::matrix::Permutation< IndexType >::get_permutation_size(), gko::Array< index_type >::operator=(), gko::matrix::Csr< ValueType, IndexType >::classical::process(), gko::matrix::Csr< ValueType, IndexType >::load_balance::process(), and gko::matrix::Csr< ValueType, IndexType >::automatical::process().
is_owning()
template<typename ValueType> bool gko::Array< ValueType >::is_owning () inline
Tells whether this Array owns its data or not.
Views do not own their data and this has multiple implications. They cannot be resized since the data is not owned by the Array which stores a view. It is also unclear whether custom deleter types are owning types as they could be a user-created view-type, therefore only proper Array which use the default_deleter are considered owning types.
Returns
whether this Array can be resized or not.
Referenced by gko::Array< index_type >::operator=(), and gko::Array< index_type >::resize_and_reset().
operator=() [1/3]
template<typename ValueType> Array& gko::Array< ValueType >::operator= (Array< ValueType > && other) inline
Moves data from another array or view.
Only the pointer and deleter type change, a copy only happens when targeting another executor's data. This means that in the following situation:
gko::Array<int> a; // an existing array or view
gko::Array<int> b; // an existing array or view
b = std::move(a);
Depending on whether a and b are array or view, this happens:
a and b are views, b becomes the only valid view of a;
a and b are arrays, b becomes the only valid array of a;
a is a view and b is an array, b frees its data and becomes the only valid view of a ();
a is an array and b is a view, b becomes the only valid array of a.
In all the previous cases, a becomes invalid (e.g., a nullptr).
This does not invoke the constructors of the elements, instead they are copied as POD types.
The executor of this is preserved. In case this does not have an assigned executor, it will inherit the executor of other.
Parameters
other the Array to move data from
Returns
this
operator=() [2/3]
template<typename ValueType> Array& gko::Array< ValueType >::operator= (const Array< ValueType > & other) inline
Copies data from another array or view.
In the case of an array target, the array is resized to match the source's size. In the case of a view target, if the dimensions are not compatible a gko::OutOfBoundsError is thrown.
This does not invoke the constructors of the elements, instead they are copied as POD types.
The executor of this is preserved. In case this does not have an assigned executor, it will inherit the executor of other.
Parameters
other the Array to copy from
Returns
this
operator=() [3/3]
template<typename ValueType> template<typename OtherValueType > xstd::enable_if_t<!std::is_same<ValueType, OtherValueType>::value, Array>& gko::Array< ValueType >::operator= (const Array< OtherValueType > & other) inline
Copies and converts data from another array with another data type.
In the case of an array target, the array is resized to match the source's size. In the case of a view target, if the dimensions are not compatible a gko::OutOfBoundsError is thrown.
This does not invoke the constructors of the elements, instead they are copied as POD types.
The executor of this is preserved. In case this does not have an assigned executor, it will inherit the executor of other.
Parameters
other the Array to copy from
Template Parameters
OtherValueType the value type of other
Returns
this
resize_and_reset()
template<typename ValueType> void gko::Array< ValueType >::resize_and_reset (size_type num_elems) inline
Resizes the array so it is able to hold the specified number of elements.
For a view and other non-owning Array types, this throws an exception since these types cannot be resized.
All data stored in the array will be lost.
If the Array is not assigned an executor, an exception will be thrown.
Parameters
num_elems the amount of memory (expressed as the number of value_type elements) allocated on the Executor
Referenced by gko::Array< index_type >::operator=().
set_executor()
template<typename ValueType> void gko::Array< ValueType >::set_executor (std::shared_ptr< const Executor > exec) inline
Changes the Executor of the Array, moving the allocated data to the new Executor.
Parameters
exec the Executor where the data will be moved to
view()
template<typename ValueType> static Array gko::Array< ValueType >::view (std::shared_ptr< const Executor > exec, size_type num_elems, value_type * data) inline static
Creates an Array from existing memory.
The Array does not take ownership of the memory, and will not deallocate it once it goes out of scope. This array type cannot use the function resize_and_reset since it does not own the data it should resize.
Parameters
exec executor where data is located
num_elems number of elements in data
data chunk of memory used to create the array
Returns
an Array constructed from data
Referenced by gko::matrix::Dense< ValueType >::create_submatrix().
The documentation for this class was generated from the following file:
ginkgo/core/base/array.hpp (a51b2818c)