Ginkgo: gko::xstd Namespace Reference
gko::xstd Namespace Reference
The namespace for functionalities after C++11 standard.
Typedefs
template<typename... Ts>
using void_t = typename detail::make_void< Ts... >::type
template<bool B, typename T = void>
using enable_if_t = typename std::enable_if< B, T >::type
template<bool B, typename T , typename F >
using conditional_t = typename std::conditional< B, T, F >::type
template<typename T >
using decay_t = typename std::decay< T >::type
Functions
template<typename T >
constexpr bool greater (const T &&lhs, const T &&rhs)
constexpr helper which checks if lhs > rhs.
template<typename T >
constexpr bool greater_equal (const T &&lhs, const T &&rhs)
constexpr helper checking if lhs >= rhs
template<typename T >
constexpr bool less (const T &&lhs, const T &&rhs)
constexpr helper checking if lhs < rhs
template<typename T >
constexpr bool less_equal (const T &&lhs, const T &&rhs)
constexpr helper checking if lhs <= rhs
Detailed Description
The namespace for functionalities after C++11 standard.
Function Documentation
greater()
template<typename T > constexpr bool gko::xstd::greater (const T && lhs, const T && rhs) constexpr
constexpr helper which checks if lhs > rhs.
This is helpful within template declarations since ">" cannot directly be used. Note that std::greater is available as constexpr only since C++14. This does not implement all the functionality of C++14, only what is needed so far.
Template Parameters
T type of both values which are checked
Parameters
lhs first operand
rhs second operand
Returns
whether lhs > rhs
Referenced by less_equal().
greater_equal()
template<typename T > constexpr bool gko::xstd::greater_equal (const T && lhs, const T && rhs) constexpr
constexpr helper checking if lhs >= rhs
Template Parameters
T type of both values which are checked
Parameters
lhs first operand
rhs second operand
Returns
whether lhs >= rhs
Referenced by less().
less()
template<typename T > constexpr bool gko::xstd::less (const T && lhs, const T && rhs) constexpr
constexpr helper checking if lhs < rhs
Template Parameters
T type of both values which are checked
Parameters
lhs first operand
rhs second operand
Returns
whether lhs < rhs
References greater_equal().
less_equal()
template<typename T > constexpr bool gko::xstd::less_equal (const T && lhs, const T && rhs) constexpr
constexpr helper checking if lhs <= rhs
Template Parameters
T type of both values which are checked
Parameters
lhs first operand
rhs second operand
Returns
whether lhs <= rhs
References greater().