name: Codehub-sync

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  sync:
    runs-on: ubuntu-latest
    name: CASTIEL2 Codehub Sync
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cniethammer/git-repo-sync@cb1067d118c0c209bcded585b5c78e581bb0dfec
      with:
        target-url: 'https://codehub.hlrs.de/coes/microcard2/ginkgo.git'
        target-username: ${{ secrets.CODEHUB_TOKEN_NAME }}
        target-token: ${{ secrets.CODEHUB_TOKEN }}
