name: JOSS-build

on:
  push:
    paths:
    - 'doc/joss/**'

jobs:
  joss-generate:
    name: joss-pandoc 
    runs-on: [ubuntu-latest] 

    steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v4

    - name: setup
      run: sudo apt-get install texlive-xetex pandoc pandoc-citeproc
    - name: info
      run: |
        pandoc -v
    - name: build 
      run: |
        pushd .
        mkdir build
        cd build
        mkdir doc
        cd doc
        cp -r ../../doc/joss ./
        cd joss
        pandoc paper.md -o paper.pdf --bibliography ./paper.bib --pdf-engine=xelatex
        popd
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: joss-paper
        path: build/doc/joss/paper.pdf 

