name: Mirroring-Develop

# only mirror on the branches other than mirror-major.yml when they contain more than documentation changes
on:
  push:
    branches-ignore:
      - 'main'
      - 'master'
      - 'develop'
      - 'release/**'
    paths-ignore:
      - 'doc/**'

jobs:
  mirror:
    name: mirror
    uses: ./.github/workflows/mirror.yml
    secrets: inherit
