name: Mirroring
# When push has condition for branch and path, both are required to be satisfied.
# Also, Github does not support two push event under on in the same file.
# We use two files distinguish the developing branches and the main branches carefully.
on: workflow_call

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: false
      - name: Push to Gitlab
        run: cp --preserve .github/mirror.sh /tmp && /tmp/mirror.sh
        env:
          BOT_KEY: ${{ secrets.GITLAB_MIRROR_PRIV_KEY }}
          BRANCH_NAME: ${{ github.ref_name }}
          GITHUB_REPO: ${{ github.repository }}
