# SPDX-FileCopyrightText: 2017-2023 The Ginkgo authors
#
# SPDX-License-Identifier: BSD-3-Clause

name: Mirroring
on: push

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: false
      - name: Push to Gitlab
        run: cp --preserve .github/mirror.sh /tmp && /tmp/mirror.sh
        env:
          BOT_KEY: ${{ secrets.GITLAB_MIRROR_PRIV_KEY }}
          BRANCH_NAME: ${{ github.ref }}
          GITHUB_REPO: ${{ github.repository }}
