name: Windows-MSVC

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
    tags:
      - '**'
  pull_request:
    types: [opened,synchronize]
    paths-ignore:
      - 'doc/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled by `debug_enabled` keyword (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ (github.head_ref && github.ref) || github.run_id }}
  cancel-in-progress: true

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-latest]
    name: msvc/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v4
    - name: Debug over SSH (tmate)
      uses: mxschmitt/action-tmate@v3.5
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      with:
        limit-access-to-actor: true

    - name: configure and test
      run: |
        $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv
        mkdir build
        cd build
        cmake -DGINKGO_BUILD_OMP=OFF -DGINKGO_BUILD_REFERENCE=OFF -DGINKGO_BUILD_EXAMPLES=OFF -DGINKGO_BUILD_BENCHMARKS=OFF -DGINKGO_BUILD_TESTS=OFF -DGINKGO_ENABLE_HALF=OFF -DGINKGO_ENABLE_BFLOAT16=OFF ..
        cmake --build . -j4 --config Release
