ginkgo_print_module_header(${detailed_log} "SYCL")
ginkgo_print_module_footer(${detailed_log} "SYCL variables:")
ginkgo_print_variable(${detailed_log} "GINKGO_SYCL_FLAGS")
ginkgo_print_variable(${detailed_log} "GINKGO_SYCL_SINGLE_MODE")
ginkgo_print_module_footer(${detailed_log} "SYCL environment variables:")
ginkgo_print_env_variable(${detailed_log} "SYCL_DEVICE_FILTER")
ginkgo_print_module_footer(${detailed_log} "")
